package ratify_test

import (
	"encoding/base64"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"testing"

	. "github.com/identities-ai/ratify-protocol"
)

// TestCrossSDKByteEquivalence loads testvectors/v1/cross_sdk_vectors.json
// (generated by cmd/ratify-testvectors) and asserts that THIS SDK produces
// byte-identical canonical output for every vector. The same fixture file
// is loaded by tests in TypeScript, Python, and Rust — hub-and-spoke design
// transitively proves all four SDKs are pairwise byte-identical.
//
// If any SDK's canonical encoding drifts, its own conformance test fails.
// If Go's encoding drifts, the generator output changes and `make
// release-check` detects the diff in CI.
func TestCrossSDKByteEquivalence(t *testing.T) {
	wd, err := os.Getwd()
	if err != nil {
		t.Fatalf("getwd: %v", err)
	}
	path := filepath.Join(wd, "testvectors", "v1", "cross_sdk_vectors.json")
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read %s: %v", path, err)
	}

	var doc struct {
		Vectors []struct {
			Kind             string          `json:"kind"`
			Name             string          `json:"name"`
			Input            json.RawMessage `json:"input"`
			ExpectedHashHex  string          `json:"expected_hash_hex"`
			ExpectedBytesB64 string          `json:"expected_bytes_b64"`
		} `json:"vectors"`
	}
	if err := json.Unmarshal(data, &doc); err != nil {
		t.Fatalf("parse: %v", err)
	}
	if len(doc.Vectors) == 0 {
		t.Fatalf("no vectors in %s", path)
	}

	for _, v := range doc.Vectors {
		v := v
		t.Run(fmt.Sprintf("%s:%s", v.Kind, v.Name), func(t *testing.T) {
			switch v.Kind {
			case "verifier_context_hash":
				checkVerifierContextHash(t, v.Input, v.ExpectedHashHex)
			case "bundle_hash":
				checkBundleHash(t, v.Input, v.ExpectedHashHex)
			case "policy_verdict_sign_bytes":
				checkPolicyVerdictSignBytes(t, v.Input, v.ExpectedBytesB64)
			case "verification_receipt_sign_bytes":
				checkVerificationReceiptSignBytes(t, v.Input, v.ExpectedBytesB64)
			default:
				t.Fatalf("unknown vector kind: %s", v.Kind)
			}
		})
	}
}

func checkVerifierContextHash(t *testing.T, raw json.RawMessage, want string) {
	t.Helper()
	var inp struct {
		HasLocation       bool    `json:"has_location"`
		HasSpeed          bool    `json:"has_speed"`
		HasAmount         bool    `json:"has_amount"`
		CurrentLat        float64 `json:"current_lat"`
		CurrentLon        float64 `json:"current_lon"`
		CurrentAltM       float64 `json:"current_alt_m"`
		CurrentSpeedMps   float64 `json:"current_speed_mps"`
		RequestedAmount   float64 `json:"requested_amount"`
		RequestedCurrency string  `json:"requested_currency"`
	}
	if err := json.Unmarshal(raw, &inp); err != nil {
		t.Fatalf("unmarshal: %v", err)
	}
	ctx := VerifierContext{
		HasLocation:       inp.HasLocation,
		HasSpeed:          inp.HasSpeed,
		HasAmount:         inp.HasAmount,
		CurrentLat:        inp.CurrentLat,
		CurrentLon:        inp.CurrentLon,
		CurrentAltM:       inp.CurrentAltM,
		CurrentSpeedMps:   inp.CurrentSpeedMps,
		RequestedAmount:   inp.RequestedAmount,
		RequestedCurrency: inp.RequestedCurrency,
	}
	got, err := VerifierContextHash(ctx)
	if err != nil {
		t.Fatalf("VerifierContextHash: %v", err)
	}
	if hex.EncodeToString(got) != want {
		t.Errorf("cross-SDK drift\n  got:  %s\n  want: %s", hex.EncodeToString(got), want)
	}
}

func checkBundleHash(t *testing.T, raw json.RawMessage, want string) {
	t.Helper()
	var inp struct {
		Bundle ProofBundle `json:"bundle"`
	}
	if err := json.Unmarshal(raw, &inp); err != nil {
		t.Fatalf("unmarshal bundle: %v", err)
	}
	got, err := BundleHash(&inp.Bundle)
	if err != nil {
		t.Fatalf("BundleHash: %v", err)
	}
	if hex.EncodeToString(got) != want {
		t.Errorf("cross-SDK drift\n  got:  %s\n  want: %s", hex.EncodeToString(got), want)
	}
}

func checkPolicyVerdictSignBytes(t *testing.T, raw json.RawMessage, want string) {
	t.Helper()
	var inp struct {
		Version        int    `json:"version"`
		VerdictID      string `json:"verdict_id"`
		AgentID        string `json:"agent_id"`
		Scope          string `json:"scope"`
		Allow          bool   `json:"allow"`
		ContextHashHex string `json:"context_hash_hex"`
		IssuedAt       int64  `json:"issued_at"`
		ValidUntil     int64  `json:"valid_until"`
	}
	if err := json.Unmarshal(raw, &inp); err != nil {
		t.Fatalf("unmarshal: %v", err)
	}
	ctxHash, err := hex.DecodeString(inp.ContextHashHex)
	if err != nil {
		t.Fatalf("decode context_hash_hex: %v", err)
	}
	v := PolicyVerdict{
		Version:     inp.Version,
		VerdictID:   inp.VerdictID,
		AgentID:     inp.AgentID,
		Scope:       inp.Scope,
		Allow:       inp.Allow,
		ContextHash: ctxHash,
		IssuedAt:    inp.IssuedAt,
		ValidUntil:  inp.ValidUntil,
	}
	got, err := PolicyVerdictSignBytes(&v)
	if err != nil {
		t.Fatalf("PolicyVerdictSignBytes: %v", err)
	}
	if base64.StdEncoding.EncodeToString(got) != want {
		t.Errorf("cross-SDK drift\n  got:  %s\n  want: %s",
			base64.StdEncoding.EncodeToString(got), want)
	}
}

func checkVerificationReceiptSignBytes(t *testing.T, raw json.RawMessage, want string) {
	t.Helper()
	var inp struct {
		Version       int      `json:"version"`
		VerifierID    string   `json:"verifier_id"`
		VerifierPub   HybridPublicKey `json:"verifier_pub"`
		BundleHashHex string   `json:"bundle_hash_hex"`
		Decision      string   `json:"decision"`
		HumanID       string   `json:"human_id"`
		AgentID       string   `json:"agent_id"`
		GrantedScope  []string `json:"granted_scope"`
		ErrorReason   string   `json:"error_reason"`
		VerifiedAt    int64    `json:"verified_at"`
		PrevHashHex   string   `json:"prev_hash_hex"`
	}
	if err := json.Unmarshal(raw, &inp); err != nil {
		t.Fatalf("unmarshal: %v", err)
	}
	bh, err := hex.DecodeString(inp.BundleHashHex)
	if err != nil {
		t.Fatalf("bundle_hash_hex: %v", err)
	}
	ph, err := hex.DecodeString(inp.PrevHashHex)
	if err != nil {
		t.Fatalf("prev_hash_hex: %v", err)
	}
	r := VerificationReceipt{
		Version:      inp.Version,
		VerifierID:   inp.VerifierID,
		VerifierPub:  inp.VerifierPub,
		BundleHash:   bh,
		Decision:     inp.Decision,
		HumanID:      inp.HumanID,
		AgentID:      inp.AgentID,
		GrantedScope: inp.GrantedScope,
		ErrorReason:  inp.ErrorReason,
		VerifiedAt:   inp.VerifiedAt,
		PrevHash:     ph,
	}
	got, err := VerificationReceiptSignBytes(&r)
	if err != nil {
		t.Fatalf("VerificationReceiptSignBytes: %v", err)
	}
	if base64.StdEncoding.EncodeToString(got) != want {
		t.Errorf("cross-SDK drift\n  got:  %s\n  want: %s",
			base64.StdEncoding.EncodeToString(got), want)
	}
}

// TestHybridKeypairFromSeedsKnownAnswer pins the deterministic keygen vector
// that every SDK implementing HybridKeypairFromSeeds must reproduce.
//
// The canonical fixtures carry no seeds, so nothing else holds the seeded
// keygen implementations to each other: an SDK could be deterministic and
// deterministically different, and every existing test would still pass. This
// vector is asserted identically in the Rust, C, and TypeScript suites.
//
// Python does not implement seeded keygen (see docs/SDKS.md), so it has no
// counterpart to this test.
func TestHybridKeypairFromSeedsKnownAnswer(t *testing.T) {
	var edSeed, mlSeed [32]byte
	for i := 0; i < 32; i++ {
		edSeed[i] = byte(i)
		mlSeed[i] = byte(0xA0 + i)
	}

	pub, priv, err := HybridKeypairFromSeeds(edSeed, mlSeed)
	if err != nil {
		t.Fatalf("HybridKeypairFromSeeds: %v", err)
	}

	const (
		wantEd25519 = "03a107bff3ce10be1d70dd18e74bc09967e4d6309ba50d5f1ddc8664125531b8"
		wantMLPrefix = "1963d47ac0e93110e3add0354e0333e31c75de34038909ec8833eb6e2aaa7218"
		wantID       = "3823136b5a5fc4c755b22704474172c0"
	)

	if got := hex.EncodeToString(pub.Ed25519); got != wantEd25519 {
		t.Errorf("ed25519 public key\n  got:  %s\n  want: %s", got, wantEd25519)
	}
	if len(pub.MLDSA65) != 1952 {
		t.Errorf("ML-DSA-65 public key length = %d, want 1952", len(pub.MLDSA65))
	}
	if got := hex.EncodeToString(pub.MLDSA65[:32]); got != wantMLPrefix {
		t.Errorf("ML-DSA-65 public key prefix\n  got:  %s\n  want: %s", got, wantMLPrefix)
	}
	if got := DeriveID(pub); got != wantID {
		t.Errorf("derived ID\n  got:  %s\n  want: %s", got, wantID)
	}

	// The same seeds must rebuild the same identity: this is the property the
	// entry exists for, and what lets an issuer persist seeds instead of keys.
	again, _, err := HybridKeypairFromSeeds(edSeed, mlSeed)
	if err != nil {
		t.Fatalf("second HybridKeypairFromSeeds: %v", err)
	}
	if DeriveID(again) != DeriveID(pub) {
		t.Error("identical seeds produced a different identity")
	}
	if priv.Ed25519 == nil {
		t.Error("private key not populated")
	}
}
