/*
 * Ratify Protocol — C/C++ bindings
 * Version: 1.0.0-alpha.20
 *
 * Cryptographic authorization for AI agents.
 * Hybrid Ed25519 + ML-DSA-65 (NIST FIPS 204).
 *
 * Apache-2.0 License — https://github.com/identities-ai/ratify-protocol
 * Documentation      — https://docs.identities.ai
 */


#ifndef RATIFY_H
#define RATIFY_H

/* DO NOT EDIT — generated by cbindgen from sdks/c/src/lib.rs */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

// Return codes for all fallible Ratify C API functions.
//
// Values 0–7 are reserved for the current version. A C `switch` must include
// a `default` case; future versions may add values.
typedef enum RatifyStatus {
    // Operation succeeded.
    RatifyOk = 0,
    // A required pointer argument was NULL.
    RatifyErrNullPointer = 1,
    // JSON parsing or serialisation failed.
    RatifyErrJson = 2,
    // Cryptographic operation failed (bad key material, invalid signature,
    // or entropy unavailable).
    RatifyErrCrypto = 3,
    // A size argument was invalid (e.g., `buf_len` != 32 for a 32-byte field).
    RatifyErrBadArgument = 4,
    // An internal error that should not occur in normal operation.
    RatifyErrInternal = 5,
    // A required argument contained invalid UTF-8.
    RatifyErrEncoding = 6,
} RatifyStatus;

typedef struct RatifyAgent RatifyAgent;

typedef struct RatifyChallengeStore RatifyChallengeStore;

typedef struct RatifyDelegationCert RatifyDelegationCert;

typedef struct RatifyHumanRoot RatifyHumanRoot;

typedef struct RatifyKeyRotation RatifyKeyRotation;

typedef struct RatifyPolicyVerdict RatifyPolicyVerdict;

typedef struct RatifyProofBundle RatifyProofBundle;

typedef struct RatifyReceipt RatifyReceipt;

typedef struct RatifyRevocationList RatifyRevocationList;

typedef struct RatifyRevocationPush RatifyRevocationPush;

typedef struct RatifySessionToken RatifySessionToken;

typedef struct RatifyTransactionReceipt RatifyTransactionReceipt;

typedef struct RatifyVerifyResult RatifyVerifyResult;

typedef struct RatifyWitnessEntry RatifyWitnessEntry;

// Application-supplied inputs for evaluating first-class constraints.
//
// Zero-initialise (`{0}` in C99) all fields you do not use. The verifier
// fails closed with `constraint_unverifiable` when a required field is absent.
//
// ```c
// RatifyVerifierContext ctx = {0};
// ctx.current_lat  = 47.6062;
// ctx.current_lon  = -122.3321;
// ctx.has_location = 1;
// ```
typedef struct RatifyVerifierContext {
    double current_lat;
    double current_lon;
    double current_alt_m;
    // 1 if the geo fields above are populated, 0 to skip geo evaluation.
    int has_location;
    double current_speed_mps;
    // 1 if speed is populated.
    int has_speed;
    double requested_amount;
    // Null-terminated ISO 4217 currency code (e.g. "USD"). NULL = no amount.
    const char *requested_currency;
    // 1 if amount fields are populated.
    int has_amount;
    // Returns how many times `cert_id` was exercised in the last `window_s`
    // seconds. NULL = skip rate evaluation (constraint fails closed).
    // The `cert_id` pointer is only valid for the duration of the callback.
    int64_t (*rate_fn)(const char *cert_id, int64_t window_s, void *userdata);
    // Passed back to `rate_fn`.
    void *rate_userdata;
} RatifyVerifierContext;

// Verifier-tracked stream context for v1.1 stream-bound bundles.
//
// Required when the bundle carries `stream_id` and `stream_seq`. Set
// `last_seen_seq = 0` for the first turn (no prior accepted turn).
//
// `stream_id` MUST point to exactly 32 bytes; `stream_id_len` MUST be 32.
// Any other value returns `RatifyErrBadArgument`.
typedef struct RatifyStreamContext {
    // Pointer to exactly 32 bytes of stream ID.
    const unsigned char *stream_id;
    // Must be exactly 32. Validated at runtime.
    uintptr_t stream_id_len;
    // Highest sequence number already accepted for this stream (0 = first turn).
    int64_t last_seen_seq;
} RatifyStreamContext;

// Full verification options for `ratify_verify_bundle_opts`.
//
// Zero-initialise (`{0}`) unused fields.
//
// ```c
// RatifyVerifyOptions opts = {0};
// opts.required_scope      = "meeting:attend";
// opts.revocation_fn       = my_revocation_callback;
// opts.revocation_userdata = my_db_handle;
// // Session binding: opts.session_context + opts.session_context_len = 32
// ```
typedef struct RatifyVerifyOptions {
    // Scope the bundle must include. NULL or empty string = no scope check.
    const char *required_scope;
    // Fixed Unix timestamp (seconds) for expiry and freshness checks.
    // 0 = use the system clock. Pass `(int64_t)time(NULL)` for current time.
    // Note: timestamp 0 (Unix epoch, 1970-01-01) is interpreted as "system clock",
    // not as the literal year 1970. Embedded systems without a synchronised RTC
    // should set this explicitly from their best available clock source.
    int64_t now_unix;
    // Pointer to `session_context_len` bytes of session context for v1.1
    // session binding. NULL = no session binding.
    // When set, `session_context_len` MUST be exactly 32.
    const unsigned char *session_context;
    // Must be 0 (no session binding) or 32. Any other value returns
    // `RatifyErrBadArgument`.
    uintptr_t session_context_len;
    // Revocation callback. NULL = no revocation check (unsafe without RevocationProvider).
    // Signature: int fn(const char *cert_id, void *userdata)
    // Returns:  1 = revoked (bundle rejected),
    //           0 = not revoked (verification continues),
    //          -1 = lookup error (bundle rejected with identity_status=invalid, fail-closed).
    int (*revocation_fn)(const char *cert_id, void *userdata);
    // Passed back to every `revocation_fn` call.
    void *revocation_userdata;
    // Constraint evaluation inputs. NULL = no constraint context; any cert
    // bearing a geo/speed/amount/rate constraint will fail closed.
    const struct RatifyVerifierContext *context;
    // Stream context for v1.1 stream-bound bundles. NULL = no stream validation.
    const struct RatifyStreamContext *stream;
} RatifyVerifyOptions;

// Resource context for `resource_path` constraints (SPEC §5.16).
//
// Deliberately a NEW struct paired with a NEW symbol
// (`ratify_verify_bundle_opts_v2`) rather than new fields on
// `RatifyVerifyOptions` / `RatifyVerifierContext`: appending to those
// ABI-visible structs would break every caller that `{0}`-initialises them
// against the old layout. This follows the versioned-options precedent set
// by `ratify_verify_bundle_opts` (SPEC §5.16). The existing symbols keep
// their exact behaviour — a bundle whose cert bears a `resource_path`
// constraint verified without this context fails closed as
// `constraint_unverifiable`.
//
// Both fields are null-terminated UTF-8, or NULL when absent. The verifier
// compares `requested_resource_id` byte-for-byte against the constraint's
// `resource_id` and matches `requested_path` under the logical path model
// of §5.7.3. Callers MUST apply every decoding/normalisation step (URL
// decode, Unicode NFC, case folding, separator conversion) BEFORE
// populating these — the verifier never transforms them.
//
// ```c
// RatifyResourceContext rc = {0};
// rc.requested_resource_id = "git:github.com/acme/widgets";
// rc.requested_path        = "/docs/setup/guide.md";
// ```
typedef struct RatifyResourceContext {
    // Null-terminated resource identifier the operation targets. NULL =
    // absent (any `resource_path` constraint fails `constraint_unverifiable`).
    const char *requested_resource_id;
    // Null-terminated logical path the operation targets. NULL = absent.
    const char *requested_path;
} RatifyResourceContext;

// Verifier-side options for `ratify_verify_streamed_turn_opts` (SPEC §5.13).
//
// Deliberately NOT `RatifyVerifyOptions`: a streamed turn re-verifies
// liveness and bindings, not the chain, so revocation callbacks and
// constraint context have no field here and can never be passed and
// silently ignored. Callers who need fresh revocation or policy semantics
// MUST run full bundle verification instead of the token fast path.
//
// Zero-initialise (`{0}`) unused fields.
typedef struct RatifyStreamedVerifyOptions {
    // Scope that must be present in the token's granted scope. NULL or
    // empty string = no scope check.
    const char *required_scope;
    // Fixed Unix timestamp (seconds) for token-window and freshness
    // checks. 0 = use the system clock.
    int64_t now_unix;
    // Verifier-side session binding the turn must match. NULL = no
    // session binding. When set, `session_context_len` MUST be exactly 32.
    const unsigned char *session_context;
    // Must be 0 (no session binding) or 32.
    uintptr_t session_context_len;
    // Verifier-side stream state. NULL = no stream validation.
    //
    // This is a caller-owned SNAPSHOT: the verifier only reads it and
    // never advances it. Two concurrent turns carrying distinct valid
    // challenges and the same stream_seq will BOTH verify against the
    // same snapshot. Concurrency-safe sequence enforcement is the
    // caller's responsibility: atomically compare-and-advance your
    // tracked last-seen sequence when (and only when) verification
    // succeeds, and build the snapshot from that tracked state.
    const struct RatifyStreamContext *stream;
} RatifyStreamedVerifyOptions;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

// Generate a new HumanRoot keypair (the delegating principal).
//
// The handle contains both the public identity and the private signing key.
// Free with `ratify_human_root_free`.
//
// # Panics
// On embedded targets where the entropy source is unavailable. This indicates
// a non-functional system; no security operation is possible.
enum RatifyStatus ratify_human_root_generate(struct RatifyHumanRoot **out);

// Free a `RatifyHumanRoot` handle. Safe to call with NULL.
void ratify_human_root_free(struct RatifyHumanRoot *handle);

// Serialise the HumanRoot public identity to JSON (no private key material).
// Free the returned string with `ratify_string_free`.
char *ratify_human_root_to_json(const struct RatifyHumanRoot *handle, char **err_out);

// Return the human root's 32-hex-character ID. Free with `ratify_string_free`.
char *ratify_human_root_id(const struct RatifyHumanRoot *handle);

// Return the human root's public key as JSON (`{"ed25519":"...","ml_dsa_65":"..."}`).
// This is the verifier public key for revocation list / push / witness verification.
// Free with `ratify_string_free`.
char *ratify_human_root_pub_key_json(const struct RatifyHumanRoot *handle, char **err_out);

// Generate a new AgentIdentity keypair.
//
// - `name_utf8` — the agent's human-readable name (null-terminated UTF-8).
// - `agent_type_utf8` — e.g. `"meeting_bot"`, `"drone"`, `"mcp_server"`, `"custom"`.
//
// Free with `ratify_agent_free`.
enum RatifyStatus ratify_agent_generate(const char *name_utf8,
                                        const char *agent_type_utf8,
                                        struct RatifyAgent **out);

// Free a `RatifyAgent` handle. Safe to call with NULL.
void ratify_agent_free(struct RatifyAgent *handle);

// Return the agent's 32-hex-character ID. Free with `ratify_string_free`.
char *ratify_agent_id(const struct RatifyAgent *handle);

// Issue a DelegationCert from a HumanRoot to an Agent.
//
// - `scopes_json` — JSON array of scope strings, e.g. `["meeting:attend"]`.
// - `issued_at_unix` — Unix timestamp for `issued_at`. Pass 0 to use the
//   system clock. Embedded targets without a synchronised RTC should set this
//   explicitly (e.g. from an NTP-synced value stored in flash).
// - `expires_at_unix` — Unix timestamp for expiry. Pass 0 for no expiry:
//   the library signs NO_EXPIRY_SENTINEL (4070908799), which means
//   "no expiry (until revoked)" per SPEC §5.7 — display and policy code
//   MUST NOT treat it as a literal 2099 expiry. See
//   `ratify_no_expiry_sentinel()` / `ratify_expires_at_is_no_expiry()`.
//
// Free with `ratify_delegation_cert_free`.
enum RatifyStatus ratify_delegation_issue(const struct RatifyHumanRoot *issuer,
                                          const struct RatifyAgent *subject,
                                          const char *scopes_json,
                                          int64_t issued_at_unix,
                                          int64_t expires_at_unix,
                                          struct RatifyDelegationCert **out,
                                          char **err_out);

// Serialise a DelegationCert to JSON. Free with `ratify_string_free`.
char *ratify_delegation_cert_to_json(const struct RatifyDelegationCert *handle, char **err_out);

// Free a `RatifyDelegationCert` handle. Safe to call with NULL.
void ratify_delegation_cert_free(struct RatifyDelegationCert *handle);

// Generate a fresh 32-byte cryptographic challenge.
//
// `buf` must point to at least `buf_len` bytes of writable memory.
// `buf_len` must be exactly 32; any other value returns `RatifyErrBadArgument`.
//
// Returns `RatifyErrCrypto` if the system's entropy source is unavailable.
enum RatifyStatus ratify_challenge_generate(unsigned char *buf, uintptr_t buf_len);

// Build a ProofBundle: the agent signs a fresh challenge with its delegation cert.
//
// - `agent` — the Agent handle (owns the signing key).
// - `cert_json` — delegation cert JSON from `ratify_delegation_cert_to_json`.
// - `challenge` — pointer to exactly `challenge_len` bytes of challenge data
//   (typically 32). `challenge_len` must be 32.
// - `challenge_at_unix` — Unix timestamp when the challenge was generated.
//   Pass `(int64_t)time(NULL)` for the current time. Must not be 0 on
//   systems where time(NULL) could legitimately return 0 — use an explicit value.
//
// Free with `ratify_proof_bundle_free`.
enum RatifyStatus ratify_proof_bundle_create(const struct RatifyAgent *agent,
                                             const char *cert_json,
                                             const unsigned char *challenge,
                                             uintptr_t challenge_len,
                                             int64_t challenge_at_unix,
                                             struct RatifyProofBundle **out,
                                             char **err_out);

// Build a ProofBundle with the protocol's 32-byte session context binding.
enum RatifyStatus ratify_proof_bundle_create_with_context(const struct RatifyAgent *agent,
                                                          const char *cert_json,
                                                          const unsigned char *challenge,
                                                          uintptr_t challenge_len,
                                                          int64_t challenge_at_unix,
                                                          const unsigned char *session_context,
                                                          uintptr_t session_context_len,
                                                          struct RatifyProofBundle **out,
                                                          char **err_out);

// Serialise a ProofBundle to JSON. Free with `ratify_string_free`.
char *ratify_proof_bundle_to_json(const struct RatifyProofBundle *handle, char **err_out);

// Free a `RatifyProofBundle` handle. Safe to call with NULL.
void ratify_proof_bundle_free(struct RatifyProofBundle *handle);

// Verify a ProofBundle JSON string — simple path (scope + clock only).
//
// Use for production embedded verifiers that need only scope enforcement and
// a fixed clock. Use `ratify_verify_bundle_opts` for revocation callbacks,
// constraint context, session binding, or stream binding.
//
// - `bundle_json` — null-terminated JSON ProofBundle string.
// - `required_scope` — null-terminated scope to require. NULL = no scope check.
// - `now_unix` — Unix timestamp for expiry/freshness. 0 = system clock.
//   Note: 0 is treated as "use system clock", not epoch year 1970.
//
// Returns `RatifyOk` whether or not the bundle is cryptographically valid.
// Inspect with `ratify_verify_result_is_valid`. Free with `ratify_verify_result_free`.
enum RatifyStatus ratify_verify_bundle(const char *bundle_json,
                                       const char *required_scope,
                                       int64_t now_unix,
                                       struct RatifyVerifyResult **out,
                                       char **err_out);

// Verify a ProofBundle JSON string with the full option set.
//
// `opts` may be NULL, which is equivalent to `ratify_verify_bundle` with
// no scope, system clock, and no additional options.
//
// Returns `RatifyErrBadArgument` if `session_context_len` is not 0 or 32,
// or if `stream_id_len` is not 0 or 32.
enum RatifyStatus ratify_verify_bundle_opts(const char *bundle_json,
                                            const struct RatifyVerifyOptions *opts,
                                            struct RatifyVerifyResult **out,
                                            char **err_out);

// Verify a ProofBundle JSON string with the full option set PLUS the
// `resource_path` resource context (SPEC §5.16).
//
// Identical to `ratify_verify_bundle_opts`, plus a `resource` pointer
// carrying the resource/path the operation targets. `resource` may be NULL
// (equivalent to the v1 symbol). This is the versioned entry point that
// extends the ABI without breaking the existing `RatifyVerifyOptions`
// layout: callers built against the older header keep working unchanged.
//
// The `MAX_PROOF_BUNDLE_BYTES` (128 KiB) input bound is enforced BEFORE
// parsing (SPEC §5.1); an oversized payload yields an `invalid` result
// rather than being parsed.
enum RatifyStatus ratify_verify_bundle_opts_v2(const char *bundle_json,
                                               const struct RatifyVerifyOptions *opts,
                                               const struct RatifyResourceContext *resource,
                                               struct RatifyVerifyResult **out,
                                               char **err_out);

// Returns 1 if the verification result is valid, 0 if invalid or handle is NULL.
int ratify_verify_result_is_valid(const struct RatifyVerifyResult *handle);

// Returns the `identity_status` string (e.g. `"authorized_agent"`, `"revoked"`).
//
// For well-known status values this returns a pointer to a static string —
// do NOT free it with `ratify_string_free`. For unknown values (future SDK
// versions) it returns a heap-allocated string that MUST be freed.
//
// In practice: always check `ratify_verify_result_is_valid` first; only call
// this for logging or diagnostics. To be safe, always call `ratify_string_free`
// on the result — freeing a static string is a no-op if the pointer is not heap-allocated.
//
// Wait — static string pointers cannot be freed via `ratify_string_free`. To avoid
// a double-free if the caller always calls free, this function ALWAYS returns a
// heap-allocated copy for safety. The static optimisation is used only internally.
char *ratify_verify_result_identity_status(const struct RatifyVerifyResult *handle);

// Returns the verified `human_id` hex string (32 characters).
// Empty string if not populated. Free with `ratify_string_free`.
char *ratify_verify_result_human_id(const struct RatifyVerifyResult *handle);

// Returns the verified `agent_id` hex string (32 characters).
// Empty string if not populated. Free with `ratify_string_free`.
char *ratify_verify_result_agent_id(const struct RatifyVerifyResult *handle);

// Returns the `error_reason` detail string when verification failed.
// Empty string on success. Free with `ratify_string_free`.
char *ratify_verify_result_error_reason(const struct RatifyVerifyResult *handle);

// Free a `RatifyVerifyResult` handle. Safe to call with NULL.
void ratify_verify_result_free(struct RatifyVerifyResult *handle);

// Free a heap-allocated string returned by any `ratify_*` accessor.
// Safe to call with NULL.
void ratify_string_free(char *s);

// Free an error string written to an `err_out` parameter.
// Safe to call with NULL.
void ratify_error_free(char *s);

// Returns the library version string. Statically allocated — do NOT free.
const char *ratify_version(void);

// Returns NO_EXPIRY_SENTINEL (4070908799 = 2099-12-31 23:59:59 UTC): the
// `expires_at` value that means "no expiry (until revoked)" per SPEC §5.7.
int64_t ratify_no_expiry_sentinel(void);

// Returns true iff `expires_at_unix` is the no-expiry sentinel. Display and
// policy code MUST branch on this rather than treating the sentinel as a
// real 2099 timestamp: a sentinel cert is an open-ended grant terminated
// only by revocation, not a ~75-year grant.
bool ratify_expires_at_is_no_expiry(int64_t expires_at_unix);

// Issue a SessionToken after a successful `ratify_verify_bundle` call.
//
// Session tokens let subsequent turns skip full chain re-verification —
// critical for embedded streaming and multi-turn Physical AI interactions.
// The verifier HMAC-signs the cached result with `session_secret`.
//
// - `bundle` — the ProofBundle that was verified.
// - `result` — the VerifyResult from ratify_verify_bundle (must be valid).
// - `session_id` — caller-assigned null-terminated session identifier.
// - `issued_at_unix` / `valid_until_unix` — validity window.
// - `session_secret` / `session_secret_len` — HMAC key, minimum 1 byte.
//   Use at least 32 bytes for security. Never share across verifier instances.
enum RatifyStatus ratify_session_token_issue(const struct RatifyProofBundle *bundle,
                                             const struct RatifyVerifyResult *result,
                                             const char *session_id,
                                             int64_t issued_at_unix,
                                             int64_t valid_until_unix,
                                             const unsigned char *session_secret,
                                             uintptr_t session_secret_len,
                                             struct RatifySessionToken **out,
                                             char **err_out);

// Verify a SessionToken JSON string against the session secret and current time.
//
// Returns `RatifyOk` if the token is cryptographically valid, within its
// validity window, and the HMAC matches. Returns `RatifyErrCrypto` otherwise;
// `*err_out` contains the specific rejection reason.
enum RatifyStatus ratify_session_token_verify(const char *token_json,
                                              const unsigned char *session_secret,
                                              uintptr_t session_secret_len,
                                              int64_t now_unix,
                                              char **err_out);

// Serialise a SessionToken to JSON. Free with `ratify_string_free`.
char *ratify_session_token_to_json(const struct RatifySessionToken *handle, char **err_out);

// Deserialise a SessionToken from JSON. Free with `ratify_session_token_free`.
enum RatifyStatus ratify_session_token_from_json(const char *json,
                                                 struct RatifySessionToken **out,
                                                 char **err_out);

// Free a `RatifySessionToken` handle. Safe to call with NULL.
void ratify_session_token_free(struct RatifySessionToken *handle);

// Issue a signed VerificationReceipt for an agent verification event.
//
// The receipt is hybrid-signed by `verifier`'s keypair and chains to
// `prev_hash` (32 bytes, or NULL/0 for the genesis receipt). Receipts form
// a tamper-evident chain: any missing or backdated entry is detectable by
// computing SHA-256 over each receipt's signable bytes.
//
// - `verifier` — the verifier's HumanRoot handle (provides ID + signing key).
// - `prev_hash` / `prev_hash_len` — NULL + 0 = genesis (zeros filled automatically).
//   Non-NULL: must be exactly 32 bytes.
enum RatifyStatus ratify_receipt_issue(const struct RatifyProofBundle *bundle,
                                       const struct RatifyVerifyResult *result,
                                       const struct RatifyHumanRoot *verifier,
                                       const unsigned char *prev_hash,
                                       uintptr_t prev_hash_len,
                                       int64_t verified_at_unix,
                                       struct RatifyReceipt **out,
                                       char **err_out);

// Verify a VerificationReceipt JSON string's hybrid signature.
// Returns `RatifyOk` if both Ed25519 and ML-DSA-65 components verify.
enum RatifyStatus ratify_receipt_verify(const char *receipt_json, char **err_out);

// Compute the SHA-256 hash of a ProofBundle's canonical bytes.
// Writes exactly 32 bytes to `out_32`. Use as `prev_hash` for the next receipt.
enum RatifyStatus ratify_bundle_hash(const struct RatifyProofBundle *bundle,
                                     unsigned char *out_32,
                                     char **err_out);

// Compute the SHA-256 hash of a VerificationReceipt's canonical bytes.
// Writes exactly 32 bytes to `out_32`. Use as `prev_hash` for the next receipt.
enum RatifyStatus ratify_receipt_hash(const struct RatifyReceipt *handle,
                                      unsigned char *out_32,
                                      char **err_out);

// Serialise a VerificationReceipt to JSON. Free with `ratify_string_free`.
char *ratify_receipt_to_json(const struct RatifyReceipt *handle, char **err_out);

// Deserialise a VerificationReceipt from JSON. Free with `ratify_receipt_free`.
enum RatifyStatus ratify_receipt_from_json(const char *json,
                                           struct RatifyReceipt **out,
                                           char **err_out);

// Free a `RatifyReceipt` handle. Safe to call with NULL.
void ratify_receipt_free(struct RatifyReceipt *handle);

// Create and sign a RevocationList from a JSON array of revoked cert IDs.
//
// The list is signed with `issuer`'s private key. Verifiers can check
// the signature offline without a network callback. Suitable for
// air-gapped embedded deployments.
//
// - `revoked_certs_json` — JSON array of cert_id hex strings.
enum RatifyStatus ratify_revocation_list_issue(const struct RatifyHumanRoot *issuer,
                                               const char *revoked_certs_json,
                                               int64_t updated_at_unix,
                                               struct RatifyRevocationList **out,
                                               char **err_out);

// Verify a RevocationList's hybrid signature against `issuer_pub_json`.
//
// `issuer_pub_json` — the issuer's public key JSON (`{"ed25519":"...","ml_dsa_65":"..."}`).
enum RatifyStatus ratify_revocation_list_verify(const char *list_json,
                                                const char *issuer_pub_json,
                                                char **err_out);

// Returns 1 if `cert_id` appears in the revocation list, 0 otherwise.
int ratify_revocation_list_contains(const struct RatifyRevocationList *handle, const char *cert_id);

// Serialise a RevocationList to JSON. Free with `ratify_string_free`.
char *ratify_revocation_list_to_json(const struct RatifyRevocationList *handle, char **err_out);

// Deserialise a RevocationList from JSON. Free with `ratify_revocation_list_free`.
enum RatifyStatus ratify_revocation_list_from_json(const char *json,
                                                   struct RatifyRevocationList **out,
                                                   char **err_out);

// Free a `RatifyRevocationList` handle. Safe to call with NULL.
void ratify_revocation_list_free(struct RatifyRevocationList *handle);

// Issue a signed RevocationPush — a real-time delta notification of newly
// revoked cert IDs. Used with push-subscription infrastructure; verifiers
// apply deltas to their local revocation cache.
//
// - `new_revoked_json` — JSON array of newly revoked cert_id strings.
// - `seq_no` — monotonically increasing sequence number per issuer.
enum RatifyStatus ratify_revocation_push_issue(const struct RatifyHumanRoot *issuer,
                                               const char *new_revoked_json,
                                               int64_t seq_no,
                                               int64_t pushed_at_unix,
                                               struct RatifyRevocationPush **out,
                                               char **err_out);

// Verify a RevocationPush's signature against `issuer_pub_json`.
enum RatifyStatus ratify_revocation_push_verify(const char *push_json,
                                                const char *issuer_pub_json,
                                                char **err_out);

// Serialise a RevocationPush to JSON. Free with `ratify_string_free`.
char *ratify_revocation_push_to_json(const struct RatifyRevocationPush *handle, char **err_out);

// Deserialise a RevocationPush from JSON. Free with `ratify_revocation_push_free`.
enum RatifyStatus ratify_revocation_push_from_json(const char *json,
                                                   struct RatifyRevocationPush **out,
                                                   char **err_out);

// Free a `RatifyRevocationPush` handle. Safe to call with NULL.
void ratify_revocation_push_free(struct RatifyRevocationPush *handle);

// Issue a signed WitnessEntry for a hash-chain audit log.
//
// - `entry_data` / `entry_data_len` — raw bytes of the witnessed payload.
// - `prev_hash` / `prev_hash_len` — NULL + 0 = genesis (zeros); otherwise 32 bytes.
// - `witness` — the witness's HumanRoot handle (ID + signing key).
enum RatifyStatus ratify_witness_entry_issue(const struct RatifyHumanRoot *witness,
                                             const unsigned char *entry_data,
                                             uintptr_t entry_data_len,
                                             int64_t timestamp_unix,
                                             const unsigned char *prev_hash,
                                             uintptr_t prev_hash_len,
                                             struct RatifyWitnessEntry **out,
                                             char **err_out);

// Verify a WitnessEntry's signature against `witness_pub_json`.
enum RatifyStatus ratify_witness_entry_verify(const char *entry_json,
                                              const char *witness_pub_json,
                                              char **err_out);

// Serialise a WitnessEntry to JSON. Free with `ratify_string_free`.
char *ratify_witness_entry_to_json(const struct RatifyWitnessEntry *handle, char **err_out);

// Deserialise a WitnessEntry from JSON. Free with `ratify_witness_entry_free`.
enum RatifyStatus ratify_witness_entry_from_json(const char *json,
                                                 struct RatifyWitnessEntry **out,
                                                 char **err_out);

// Free a `RatifyWitnessEntry` handle. Safe to call with NULL.
void ratify_witness_entry_free(struct RatifyWitnessEntry *handle);

// Issue a KeyRotationStatement signed by BOTH the old and new root keys.
//
// Use this when rotating a device's identity keypair (e.g., after key
// compromise or scheduled rotation). The statement proves continuity:
// the old key authorises the new key.
//
// - `old_root` — the old HumanRoot handle (will sign).
// - `new_root` — the new HumanRoot handle (will also sign).
// - `reason` — null-terminated reason string (e.g., "scheduled_rotation").
enum RatifyStatus ratify_key_rotation_issue(const struct RatifyHumanRoot *old_root,
                                            const struct RatifyHumanRoot *new_root,
                                            const char *reason,
                                            int64_t rotated_at_unix,
                                            struct RatifyKeyRotation **out,
                                            char **err_out);

// Verify a KeyRotationStatement — checks both old and new key signatures.
enum RatifyStatus ratify_key_rotation_verify(const char *stmt_json, char **err_out);

// Serialise a KeyRotationStatement to JSON. Free with `ratify_string_free`.
char *ratify_key_rotation_to_json(const struct RatifyKeyRotation *handle, char **err_out);

// Deserialise a KeyRotationStatement from JSON. Free with `ratify_key_rotation_free`.
enum RatifyStatus ratify_key_rotation_from_json(const char *json,
                                                struct RatifyKeyRotation **out,
                                                char **err_out);

// Free a `RatifyKeyRotation` handle. Safe to call with NULL.
void ratify_key_rotation_free(struct RatifyKeyRotation *handle);

// Returns 1 if `required` appears in the JSON array of granted scopes.
// Returns 0 if absent, if either pointer is null, or on parse error.
int ratify_scope_has(const char *granted_json, const char *required);

// Returns 1 if `scope` is marked sensitive in the protocol vocabulary
// (i.e., requires high-assurance verification), 0 otherwise.
// NULL or non-UTF-8 input returns 0.
int ratify_scope_is_sensitive(const char *scope);

// Expand wildcard scopes to their concrete members.
// Input: JSON array e.g. `["meeting:*"]`.
// Output: JSON array of expanded concrete scopes.
// Free with `ratify_string_free`. Returns NULL on parse error (`*err_out` set).
char *ratify_scopes_expand(const char *scopes_json, char **err_out);

// Compute the intersection of multiple scope arrays.
//
// `scope_arrays_json` — pointer to `count` null-terminated JSON array strings.
// Returns JSON array of scopes present in ALL arrays. Free with `ratify_string_free`.
char *ratify_scopes_intersect(const char *const *scope_arrays_json,
                              uintptr_t count,
                              char **err_out);

// Validate a JSON array of scope strings against the protocol vocabulary.
//
// Returns NULL if all scopes are valid. Returns a heap-allocated error string
// (free with `ratify_string_free`) if any scope is invalid. NULL input returns
// a null-pointer error string.
char *ratify_scopes_validate(const char *scopes_json);

// Return the complete canonical scope vocabulary for v1 as a JSON array of
// strings, sorted lexicographically.
//
// Consumers that present scope choices to users (consoles, policy editors)
// should derive their lists from this function rather than hardcoding scope
// strings, so UI vocabularies cannot drift from the protocol.
//
// Free with `ratify_string_free`. Returns NULL only on allocation failure.
char *ratify_scope_vocabulary(void);

// Issue a HMAC-bound PolicyVerdict — a cached policy decision.
//
// After a policy server evaluates a bundle, it can issue a short-lived verdict
// that subsequent verifications can consume locally without re-running the
// policy engine. The verdict is bound to (agent_id, scope, context_hash) so
// it cannot be replayed across different agents or contexts.
//
// - `context_hash` / `context_hash_len` — exactly 32 bytes. Compute with
//   `ratify_verifier_context_hash` to bind to a specific VerifierContext.
// - `policy_secret` — HMAC key; minimum 1 byte, 32+ bytes recommended.
// - `allow` — 1 for allow, 0 for deny.
enum RatifyStatus ratify_policy_verdict_issue(const char *verdict_id,
                                              const char *agent_id,
                                              const char *scope,
                                              int allow,
                                              const unsigned char *context_hash,
                                              uintptr_t context_hash_len,
                                              int64_t issued_at_unix,
                                              int64_t valid_until_unix,
                                              const unsigned char *policy_secret,
                                              uintptr_t policy_secret_len,
                                              struct RatifyPolicyVerdict **out,
                                              char **err_out);

// Verify a PolicyVerdict JSON string.
//
// Returns `RatifyOk` if the verdict is valid (HMAC matches, not expired, agent/scope/context match, and allow=true).
// Returns `RatifyErrCrypto` with a reason if invalid or if the verdict is a cached deny.
enum RatifyStatus ratify_policy_verdict_verify(const char *verdict_json,
                                               const unsigned char *policy_secret,
                                               uintptr_t policy_secret_len,
                                               const char *expected_agent_id,
                                               const char *expected_scope,
                                               const unsigned char *expected_context_hash,
                                               uintptr_t expected_context_hash_len,
                                               int64_t now_unix,
                                               char **err_out);

// Serialise a PolicyVerdict to JSON. Free with `ratify_string_free`.
char *ratify_policy_verdict_to_json(const struct RatifyPolicyVerdict *handle, char **err_out);

// Deserialise a PolicyVerdict from JSON. Free with `ratify_policy_verdict_free`.
enum RatifyStatus ratify_policy_verdict_from_json(const char *json,
                                                  struct RatifyPolicyVerdict **out,
                                                  char **err_out);

// Free a `RatifyPolicyVerdict` handle. Safe to call with NULL.
void ratify_policy_verdict_free(struct RatifyPolicyVerdict *handle);

// Verify a multi-party TransactionReceipt JSON string.
//
// Verifies every party signature independently and returns `RatifyOk` only
// if ALL party signatures verify.
//
// - `now_unix` — Unix timestamp used for party proof bundle freshness checks.
//   Pass 0 to use the system clock. Embedded targets without a system clock
//   should pass an explicit timestamp from their best available time source.
enum RatifyStatus ratify_transaction_receipt_verify(const char *receipt_json,
                                                    int64_t now_unix,
                                                    char **err_out);

// Sign a TransactionReceipt as one party using an AgentIdentity.
//
// Returns the party signature as a JSON string (`ReceiptPartySignature`).
// Free with `ratify_string_free`. The caller collects all party signatures
// and assembles the final receipt.
char *ratify_transaction_receipt_sign_party(const char *receipt_json,
                                            const char *party_id,
                                            const struct RatifyAgent *agent,
                                            char **err_out);

// Deserialise a TransactionReceipt from JSON. Free with `ratify_transaction_receipt_free`.
enum RatifyStatus ratify_transaction_receipt_from_json(const char *json,
                                                       struct RatifyTransactionReceipt **out,
                                                       char **err_out);

// Serialise a TransactionReceipt to JSON. Free with `ratify_string_free`.
char *ratify_transaction_receipt_to_json(const struct RatifyTransactionReceipt *handle,
                                         char **err_out);

// Free a `RatifyTransactionReceipt` handle. Safe to call with NULL.
void ratify_transaction_receipt_free(struct RatifyTransactionReceipt *handle);

// Compute the SHA-256 hash of a delegation cert chain.
//
// Writes exactly 32 bytes to `out_32`. Used as `chain_hash` in SessionTokens
// to bind a session to a specific delegation chain — if any cert in the chain
// is replaced, the hash changes and the session token is invalidated.
enum RatifyStatus ratify_chain_hash(const struct RatifyProofBundle *bundle,
                                    unsigned char *out_32,
                                    char **err_out);

// Compute the SHA-256 hash of a VerifierContext.
//
// Writes exactly 32 bytes to `out_32`. Use this as the `context_hash` when
// issuing a PolicyVerdict to bind the verdict to a specific constraint
// evaluation context.
enum RatifyStatus ratify_verifier_context_hash(const struct RatifyVerifierContext *ctx,
                                               unsigned char *out_32,
                                               char **err_out);

// Return the canonical revocation-list signing bytes as a lowercase hex string.
char *ratify_revocation_list_sign_bytes_hex(const char *list_json, char **err_out);

// Return the canonical revocation-push signing bytes as a lowercase hex string.
char *ratify_revocation_push_sign_bytes_hex(const char *push_json, char **err_out);

// Return the Ed25519 component of a RevocationPush signature as hex. Free with `ratify_string_free`.
char *ratify_revocation_push_sig_ed25519_hex(const char *push_json,
                                             char **err_out);

// Return the ML-DSA-65 component of a RevocationPush signature as hex. Free with `ratify_string_free`.
char *ratify_revocation_push_sig_ml_dsa_65_hex(const char *push_json,
                                               char **err_out);

// Return the canonical key-rotation signing bytes as a lowercase hex string.
char *ratify_key_rotation_sign_bytes_hex(const char *rotation_json, char **err_out);

// Return the canonical session-token signing bytes as a lowercase hex string.
char *ratify_session_token_sign_bytes_hex(const char *token_json, char **err_out);

// Return the session-token MAC bytes as a lowercase hex string. Free with `ratify_string_free`.
char *ratify_session_token_mac_hex(const char *token_json, char **err_out);

// Return the canonical transaction-receipt signing bytes as a lowercase hex string.
char *ratify_transaction_receipt_sign_bytes_hex(const char *receipt_json, char **err_out);

// Return the canonical witness-entry signing bytes as a lowercase hex string.
char *ratify_witness_entry_sign_bytes_hex(const char *entry_json, char **err_out);

// Return the Ed25519 component of a WitnessEntry signature as hex. Free with `ratify_string_free`.
char *ratify_witness_entry_sig_ed25519_hex(const char *entry_json, char **err_out);

// Return the ML-DSA-65 component of a WitnessEntry signature as hex. Free with `ratify_string_free`.
char *ratify_witness_entry_sig_ml_dsa_65_hex(const char *entry_json,
                                             char **err_out);

// Verify a single streamed turn against an already-issued session token.
//
// DEPRECATED: presentation checks only — this form cannot enforce a
// required scope, single-use challenges, or verifier-side session/stream
// checks, so a token holder passes it for any protected action. Use
// `ratify_verify_streamed_turn_opts`. Retained for compatibility through
// the v1.0.0-* releases.
//
// This is the fast path for embedded streaming: after a full `verify_bundle`
// that issued a session token, each subsequent turn is verified with this
// function — no cert chain re-verification needed.
//
// Returns a `RatifyVerifyResult*` (same type as `ratify_verify_bundle`).
// Free with `ratify_verify_result_free`.
//
// - `token_json`          — JSON of the `SessionToken` returned by `ratify_session_token_issue`.
// - `session_secret`      — the HMAC secret used when the token was issued (raw bytes, ≥1 byte).
// - `challenge` / `challenge_len` — the fresh challenge bytes for this turn.
// - `challenge_at`        — Unix timestamp the challenge was issued.
// - `challenge_sig_json`  — `HybridSignature` JSON produced by the agent.
// - `session_context`     — optional 32-byte session context (NULL + 0 = none).
// - `stream_id`           — optional 32-byte stream ID (NULL + 0 = none).
// - `stream_seq`          — highest sequence number already accepted (0 = first turn).
// - `now_unix`            — current clock; 0 = use system clock.
struct RatifyVerifyResult *ratify_verify_streamed_turn(const char *token_json,
                                                       const unsigned char *session_secret,
                                                       uintptr_t session_secret_len,
                                                       const unsigned char *challenge,
                                                       uintptr_t challenge_len,
                                                       int64_t challenge_at,
                                                       const char *challenge_sig_json,
                                                       const unsigned char *session_context,
                                                       uintptr_t session_context_len,
                                                       const unsigned char *stream_id,
                                                       uintptr_t stream_id_len,
                                                       int64_t stream_seq,
                                                       int64_t now_unix,
                                                       char **err_out);

// Options-object streamed-turn verification (SPEC §5.13).
//
// Verifies one turn against a previously issued SessionToken and enforces
// the verifier-side controls the positional `ratify_verify_streamed_turn`
// cannot: `opts->required_scope` is checked against the token's cached
// effective scope (`scope_denied` on miss), `opts->session_context` /
// `opts->stream` are the verifier-side expectations checked against the
// presented bindings with the same statuses as full verification, and a
// non-NULL `store` makes the per-turn challenge single-use (consulted,
// without consuming, after the session token's HMAC authenticates the
// presentation and before the per-turn hybrid challenge signature is
// verified; atomically consumed after that signature verifies — before
// the scope check; store failures normalize to the canonical
// unknown_challenge result).
//
// `opts` is `RatifyStreamedVerifyOptions` — deliberately not the full
// `RatifyVerifyOptions`, so revocation callbacks and constraint context
// can never be passed and silently ignored. Callers who need fresh
// revocation or policy semantics run full bundle verification instead.
//
// - `session_context` / `stream_id` / `stream_seq` — the PRESENTED
//   bindings the agent signed (NULL + 0 = unbound), distinct from the
//   expectations in `opts`.
// - `opts` may be NULL for default options; `now` comes from
//   `opts->now_unix` (0 = system clock).
// - `store` may be NULL to skip single-use enforcement.
// - `opts->stream` is a caller-owned snapshot — see its declaration for
//   the atomic-advance requirement.
enum RatifyStatus ratify_verify_streamed_turn_opts(const char *token_json,
                                                   const unsigned char *session_secret,
                                                   uintptr_t session_secret_len,
                                                   const unsigned char *challenge,
                                                   uintptr_t challenge_len,
                                                   int64_t challenge_at,
                                                   const char *challenge_sig_json,
                                                   const unsigned char *session_context,
                                                   uintptr_t session_context_len,
                                                   const unsigned char *stream_id,
                                                   uintptr_t stream_id_len,
                                                   int64_t stream_seq,
                                                   const struct RatifyStreamedVerifyOptions *opts,
                                                   const struct RatifyChallengeStore *store,
                                                   struct RatifyVerifyResult **out,
                                                   char **err_out);

// Full transaction-receipt verification with explicit valid/error_reason outputs.
//
// Writes 1 to `*valid_out` on success, 0 on failure.
// On failure, `*err_out` contains the error_reason string (free with `ratify_error_free`).
// Returns `RatifyOk` on parse success (the receipt may still be invalid — check `*valid_out`).
enum RatifyStatus ratify_transaction_receipt_verify_full(const char *receipt_json,
                                                         int64_t now_unix,
                                                         int *valid_out,
                                                         char **err_out);

// Compute the 32-byte request_hash over the SPEC §6.4.9 operation
// context: the specific action a presentation authorizes. Every string
// may be NULL (= empty); `payload_digest` is NULL + 0 (= none) or
// exactly 32 bytes. Writes 32 bytes to `out_hash`.
//
// Feed the result to `ratify_session_context_build` as `request_hash` —
// binding the session but not the operation would let an intermediary
// attach a valid proof to the wrong action inside the right session.
enum RatifyStatus ratify_operation_context_hash(const char *required_scope,
                                                const char *operation,
                                                const char *resource_id,
                                                const char *requested_path,
                                                const unsigned char *payload_digest,
                                                uintptr_t payload_digest_len,
                                                unsigned char *out_hash,
                                                char **err_out);

// Build the 32-byte session_context over the SPEC §6.4.9 session
// context: the session a presentation belongs to plus (through
// `request_hash`) the operation it authorizes. Every string may be NULL
// (= empty); `request_hash` MUST be exactly 32 bytes — from
// `ratify_operation_context_hash`, over an all-NULL operation context
// when the deployment has no operation-specific inputs. Writes 32 bytes
// to `out_context`, ready for `RatifyVerifyOptions.session_context` and
// the challenge signing bytes. The Middleware Custody Profile (SPEC
// §15.2.1) requires all fields populated.
enum RatifyStatus ratify_session_context_build(const char *verifier_id,
                                               const char *workspace_id,
                                               const char *agent_id,
                                               const char *session_id,
                                               const char *invocation_id,
                                               const unsigned char *request_hash,
                                               uintptr_t request_hash_len,
                                               unsigned char *out_context,
                                               char **err_out);

// Create an in-memory challenge store holding at most `max_size` pending
// challenges. The store makes verifier-issued challenges single-use: each
// is accepted at most once within its freshness window; consuming a
// challenge removes its record, freeing the capacity slot immediately.
// Single-process only — deployments spanning processes or hosts need a
// store over shared storage with atomic consumption. Returns NULL when
// `max_size` is 0. Free with `ratify_challenge_store_free`.
struct RatifyChallengeStore *ratify_challenge_store_new(uintptr_t max_size);

// Free a `RatifyChallengeStore` handle. Safe to call with NULL.
void ratify_challenge_store_free(struct RatifyChallengeStore *store);

// Issue a fresh 32-byte challenge bound to `session_context` (which must
// be NULL/0 = unbound, or exactly 32 bytes), valid for `ttl_seconds`
// (which must be positive). Invalid inputs return RatifyErrBadArgument.
//
// - `out_challenge` — buffer of at least 32 bytes; receives the challenge.
// - `out_expires_at` — optional; receives the expiry (unix seconds).
enum RatifyStatus ratify_challenge_store_issue(const struct RatifyChallengeStore *store,
                                               const unsigned char *session_context,
                                               uintptr_t session_context_len,
                                               int64_t ttl_seconds,
                                               unsigned char *out_challenge,
                                               int64_t *out_expires_at,
                                               char **err_out);

// Report whether `challenge` could be consumed right now — issued,
// unexpired, unconsumed, and bound to `session_context` — WITHOUT
// consuming it. Returns RatifyOk when consumable; otherwise an error
// status with the documented unknown-challenge detail in `*err_out`.
// `now_unix` 0 = system clock.
enum RatifyStatus ratify_challenge_store_check(const struct RatifyChallengeStore *store,
                                               const unsigned char *challenge,
                                               uintptr_t challenge_len,
                                               const unsigned char *session_context,
                                               uintptr_t session_context_len,
                                               int64_t now_unix,
                                               char **err_out);

// Atomically remove the challenge's issuance record. Exactly one consume
// of a given challenge may ever succeed; later calls (and calls with a
// mismatched `session_context`, which do NOT remove the record) return an
// error status with the documented unknown-challenge detail in `*err_out`.
// Removal frees the record's capacity slot immediately.
// `now_unix` 0 = system clock.
enum RatifyStatus ratify_challenge_store_consume(const struct RatifyChallengeStore *store,
                                                 const unsigned char *challenge,
                                                 uintptr_t challenge_len,
                                                 const unsigned char *session_context,
                                                 uintptr_t session_context_len,
                                                 int64_t now_unix,
                                                 char **err_out);

// Verify a ProofBundle with single-use challenge enforcement (SPEC §10).
//
// Identical to `ratify_verify_bundle_opts`, plus: the store is consulted
// (without consuming) before any signature work, and the challenge is
// atomically consumed after the structural, chain, and challenge-signature
// checks pass — before authorization evaluation. A forged or malformed
// presentation never consumes a challenge; a cryptographically valid
// presentation does, even if authorization is subsequently denied.
//
// The store's session binding is checked against `opts->session_context`.
// `opts` may be NULL for default options.
enum RatifyStatus ratify_verify_bundle_opts_with_challenge_store(const char *bundle_json,
                                                                 const struct RatifyVerifyOptions *opts,
                                                                 const struct RatifyChallengeStore *store,
                                                                 struct RatifyVerifyResult **out,
                                                                 char **err_out);

// Compute the 16-byte hex identity from a hybrid public key (SPEC §7).
//
// `pub_json` is the public key JSON (`{"ed25519":"...","ml_dsa_65":"..."}`),
// as returned by `ratify_human_root_pub_key_json`. Free the result with
// `ratify_string_free`.
//
// A verifier that pins an identity by id uses this to confirm that a public
// key it has been given belongs to the principal it pinned (SPEC §15.4).
char *ratify_derive_id(const char *pub_json, char **err_out);

// Return the canonical delegation-cert signing bytes as a lowercase hex string.
char *ratify_delegation_sign_bytes_hex(const char *cert_json, char **err_out);

// Return the challenge signing bytes as a lowercase hex string.
//
// One entry point covers all three challenge-bytes variants in
// `docs/SDKS.md` §4, which explicitly permits optional arguments where that is
// idiomatic:
//
// - plain (`challenge || BE u64(ts)`): pass NULL for both optional pointers;
// - session-bound (SPEC §5.8): pass a 32-byte `session_context`;
// - stream-bound: additionally pass a 32-byte `stream_id` and `stream_seq`.
//
// `challenge` must point to exactly `challenge_len` bytes. `session_context`
// and `stream_id`, when non-NULL, MUST each be exactly 32 bytes.
char *ratify_challenge_sign_bytes_hex(const unsigned char *challenge,
                                      uintptr_t challenge_len,
                                      int64_t challenge_at_unix,
                                      const unsigned char *session_context,
                                      uintptr_t session_context_len,
                                      const unsigned char *stream_id,
                                      uintptr_t stream_id_len,
                                      int64_t stream_seq,
                                      char **err_out);

// Canonicalise a JSON document (SPEC §6). Returns the canonical form as a
// string; free with `ratify_string_free`. Provided for interop audit, which is
// what §4 names it for.
char *ratify_canonical_json(const char *json, char **err_out);

// Rebuild a HumanRoot deterministically from two 32-byte seeds.
//
// This is the supported way to persist an issuer identity in C: store the two
// seeds as key material and reconstruct the identity after a restart. The
// protocol deliberately specifies no private-key serialisation format, so
// seeds are the portable unit.
//
// `created_at_unix` is carried into the rebuilt identity so that a restored
// root is byte-identical to the original rather than merely equivalent.
//
// Both seeds MUST be 32 bytes and MUST come from a cryptographically secure
// source. Anyone holding them holds the identity.
enum RatifyStatus ratify_human_root_from_seeds(const unsigned char *ed_seed,
                                               uintptr_t ed_seed_len,
                                               const unsigned char *ml_seed,
                                               uintptr_t ml_seed_len,
                                               int64_t created_at_unix,
                                               struct RatifyHumanRoot **out,
                                               char **err_out);

// Rebuild an AgentIdentity deterministically from two 32-byte seeds.
// See `ratify_human_root_from_seeds` for the seed-custody warning.
enum RatifyStatus ratify_agent_from_seeds(const char *name_utf8,
                                          const char *agent_type_utf8,
                                          const unsigned char *ed_seed,
                                          uintptr_t ed_seed_len,
                                          const unsigned char *ml_seed,
                                          uintptr_t ml_seed_len,
                                          int64_t created_at_unix,
                                          struct RatifyAgent **out,
                                          char **err_out);

// Verify a delegation cert's own hybrid signature. Writes 1 or 0 to
// `valid_out`. This checks only the signature on this one cert; full chain
// verification is `ratify_verify_bundle`.
enum RatifyStatus ratify_verify_delegation_signature(const char *cert_json,
                                                     int *valid_out,
                                                     char **err_out);

// Sign a challenge with an agent's private key, returning the hybrid
// signature as JSON. Free with `ratify_string_free`.
//
// Optional bindings match `ratify_challenge_sign_bytes_hex`: pass NULL for
// both to sign the plain preimage, a 32-byte `session_context` for the
// session-bound form, and additionally a 32-byte `stream_id` plus
// `stream_seq` for the stream-bound form.
char *ratify_agent_sign_challenge(const struct RatifyAgent *agent,
                                  const unsigned char *challenge,
                                  uintptr_t challenge_len,
                                  int64_t challenge_at_unix,
                                  const unsigned char *session_context,
                                  uintptr_t session_context_len,
                                  const unsigned char *stream_id,
                                  uintptr_t stream_id_len,
                                  int64_t stream_seq,
                                  char **err_out);

// Verify a hybrid challenge signature against a public key. Writes 1 or 0 to
// `valid_out`. Optional bindings match `ratify_agent_sign_challenge`; they
// MUST match what was signed or verification fails.
enum RatifyStatus ratify_verify_challenge_signature(const unsigned char *challenge,
                                                    uintptr_t challenge_len,
                                                    int64_t challenge_at_unix,
                                                    const unsigned char *session_context,
                                                    uintptr_t session_context_len,
                                                    const unsigned char *stream_id,
                                                    uintptr_t stream_id_len,
                                                    int64_t stream_seq,
                                                    const char *sig_json,
                                                    const char *pub_json,
                                                    int *valid_out,
                                                    char **err_out);

// Generate a random hybrid keypair from the OS RNG.
//
// The public half is returned as JSON. The private half is returned as the
// two 32-byte seeds that reproduce it through `ratify_human_root_from_seeds`
// or `ratify_agent_from_seeds`: the protocol specifies no private-key
// serialisation format, so seeds are this SDK's portable unit of private key
// material. Both output buffers MUST be at least 32 bytes. Treat them as key
// material.
enum RatifyStatus ratify_generate_hybrid_keypair(char **out_pub_json,
                                                 unsigned char *out_ed_seed,
                                                 unsigned char *out_ml_seed,
                                                 char **err_out);

// Return the operation-context preimage (SPEC §6.4.9) as a lowercase hex
// string. `ratify_operation_context_hash` returns the digest over these bytes;
// audit tooling needs the bytes themselves. Parameters match that function.
char *ratify_operation_context_bytes_hex(const char *required_scope,
                                         const char *operation,
                                         const char *resource_id,
                                         const char *requested_path,
                                         const unsigned char *payload_digest,
                                         uintptr_t payload_digest_len,
                                         char **err_out);

// Return the session-context preimage (SPEC §6.4.9) as a lowercase hex
// string. Parameters match `ratify_session_context_build`, which returns the
// digest over these bytes.
char *ratify_session_context_bytes_hex(const char *verifier_id,
                                       const char *workspace_id,
                                       const char *agent_id,
                                       const char *session_id,
                                       const char *invocation_id,
                                       const unsigned char *request_hash,
                                       uintptr_t request_hash_len,
                                       char **err_out);

// Serialise an agent's hybrid public key to JSON, for feeding to
// `ratify_verify_challenge_signature` and `ratify_derive_id`. The symmetric
// accessor for human roots already existed; without this one an agent's key
// could not be handed to the verification primitives at all. Free with
// `ratify_string_free`.
char *ratify_agent_pub_key_json(const struct RatifyAgent *agent, char **err_out);

// Register a custom entropy callback for platforms without OS-level RNG.
//
// `callback` must:
// - Write exactly `len` cryptographically random bytes to `buf`.
// - Return 0 on success, non-zero if insufficient entropy is available
//   (the library will panic rather than use weak randomness).
// - Be thread-safe if `ratify_*` functions are called from multiple threads.
//
// Call this once at startup, before any delegation or challenge operation.
// On FreeRTOS with an STM32 TRNG:
//   ```c
//   int my_entropy(uint8_t *buf, size_t len) {
//       for (size_t i = 0; i < len; i += 4) {
//           uint32_t rnd;
//           if (HAL_RNG_GenerateRandomNumber(&hrng, &rnd) != HAL_OK) return -1;
//           memcpy(buf + i, &rnd, (len - i < 4) ? len - i : 4);
//       }
//       return 0;
//   }
//   ratify_set_entropy_source(my_entropy);
//   ```
void ratify_set_entropy_source(int32_t (*callback)(uint8_t *buf, uintptr_t len));

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* RATIFY_H */
