"""Cross-SDK byte-equivalence corpus consumer (SPEC §17.5–§17.6).

Loads testvectors/v1/cross_sdk_vectors.json (generated by
cmd/ratify-testvectors) and asserts that this SDK produces byte-identical
output to the Go reference for every vector:

  - verifier_context_hash
  - bundle_hash
  - policy_verdict_sign_bytes
  - verification_receipt_sign_bytes

Hub-and-spoke: Go generates expected bytes; TS, Python, and Rust each
assert against them. Transitively proves all four SDKs are pairwise
byte-identical without N×N assertions.
"""
from __future__ import annotations

import base64
import json
from pathlib import Path

import pytest

from ratify_protocol import (
    Constraint,
    DelegationCert,
    HybridPublicKey,
    HybridSignature,
    PolicyVerdict,
    ProofBundle,
    VerificationReceipt,
    VerifierContext,
    bundle_hash,
    policy_verdict_sign_bytes,
    verification_receipt_sign_bytes,
    verifier_context_hash,
)

VECTOR_PATH = (
    Path(__file__).resolve().parents[3]
    / "testvectors"
    / "v1"
    / "cross_sdk_vectors.json"
)


def _b64(b: bytes) -> str:
    return base64.b64encode(b).decode()


def _b64d(s: str) -> bytes:
    return base64.b64decode(s)


with VECTOR_PATH.open() as f:
    _DOC = json.load(f)

_VECTORS = _DOC["vectors"]
assert _VECTORS, f"no vectors in {VECTOR_PATH}"


def _ids(v):
    return f"{v['kind']}:{v['name']}"


@pytest.mark.parametrize("v", _VECTORS, ids=_ids)
def test_cross_sdk_vector(v):
    kind = v["kind"]
    inp = v["input"]
    if kind == "verifier_context_hash":
        ctx = VerifierContext()
        if inp.get("has_location"):
            ctx.current_lat = inp["current_lat"]
            ctx.current_lon = inp["current_lon"]
            ctx.current_alt_m = inp["current_alt_m"]
        if inp.get("has_speed"):
            ctx.current_speed_mps = inp["current_speed_mps"]
        if inp.get("has_amount"):
            ctx.requested_amount = inp["requested_amount"]
            ctx.requested_currency = inp["requested_currency"]
        got = verifier_context_hash(ctx).hex()
        assert got == v["expected_hash_hex"], (
            f"cross-SDK drift for {v['name']}; Python diverged from Go reference"
        )
    elif kind == "bundle_hash":
        raw = inp["bundle"]
        bundle = ProofBundle(
            agent_id=raw["agent_id"],
            agent_pub_key=HybridPublicKey(
                ed25519=_b64d(raw["agent_pub_key"]["ed25519"]),
                ml_dsa_65=_b64d(raw["agent_pub_key"]["ml_dsa_65"]),
            ),
            delegations=[
                DelegationCert(
                    cert_id=d["cert_id"],
                    version=d["version"],
                    issuer_id=d["issuer_id"],
                    issuer_pub_key=HybridPublicKey(
                        ed25519=_b64d(d["issuer_pub_key"]["ed25519"]),
                        ml_dsa_65=_b64d(d["issuer_pub_key"]["ml_dsa_65"]),
                    ),
                    subject_id=d["subject_id"],
                    subject_pub_key=HybridPublicKey(
                        ed25519=_b64d(d["subject_pub_key"]["ed25519"]),
                        ml_dsa_65=_b64d(d["subject_pub_key"]["ml_dsa_65"]),
                    ),
                    scope=list(d["scope"]),
                    constraints=[
                        Constraint(**{k: v for k, v in c.items()})
                        for c in d.get("constraints", [])
                    ],
                    issued_at=d["issued_at"],
                    expires_at=d["expires_at"],
                    signature=HybridSignature(
                        ed25519=_b64d(d["signature"]["ed25519"]),
                        ml_dsa_65=_b64d(d["signature"]["ml_dsa_65"]),
                    ),
                )
                for d in raw["delegations"]
            ],
            challenge=_b64d(raw["challenge"]),
            challenge_at=raw["challenge_at"],
            challenge_sig=HybridSignature(
                ed25519=_b64d(raw["challenge_sig"]["ed25519"]),
                ml_dsa_65=_b64d(raw["challenge_sig"]["ml_dsa_65"]),
            ),
        )
        got = bundle_hash(bundle).hex()
        assert got == v["expected_hash_hex"], (
            f"cross-SDK drift for {v['name']}"
        )
    elif kind == "policy_verdict_sign_bytes":
        verdict = PolicyVerdict(
            version=inp["version"],
            verdict_id=inp["verdict_id"],
            agent_id=inp["agent_id"],
            scope=inp["scope"],
            allow=inp["allow"],
            context_hash=bytes.fromhex(inp["context_hash_hex"]),
            issued_at=inp["issued_at"],
            valid_until=inp["valid_until"],
            mac=b"",
        )
        got = _b64(policy_verdict_sign_bytes(verdict))
        assert got == v["expected_bytes_b64"], (
            f"cross-SDK drift for {v['name']}"
        )
    elif kind == "verification_receipt_sign_bytes":
        receipt = VerificationReceipt(
            version=inp["version"],
            verifier_id=inp["verifier_id"],
            verifier_pub=HybridPublicKey(
                ed25519=_b64d(inp["verifier_pub"]["ed25519"]),
                ml_dsa_65=_b64d(inp["verifier_pub"]["ml_dsa_65"]),
            ),
            bundle_hash=bytes.fromhex(inp["bundle_hash_hex"]),
            decision=inp["decision"],
            human_id=inp.get("human_id", ""),
            agent_id=inp.get("agent_id", ""),
            granted_scope=list(inp.get("granted_scope", [])),
            error_reason=inp.get("error_reason", ""),
            verified_at=inp["verified_at"],
            prev_hash=bytes.fromhex(inp["prev_hash_hex"]),
            signature=HybridSignature(ed25519=b"", ml_dsa_65=b""),
        )
        got = _b64(verification_receipt_sign_bytes(receipt))
        assert got == v["expected_bytes_b64"], (
            f"cross-SDK drift for {v['name']}"
        )
    else:
        raise AssertionError(f"unknown cross-SDK vector kind: {kind}")
