//! Ratify Protocol — C/C++ FFI bindings.
//!
//! Exposes the Ratify Protocol Rust SDK as a C-compatible ABI producing:
//! - `libratify_c.a`  — static library for embedded/RTOS targets
//! - `libratify_c.so` / `.dylib` / `.dll` — shared library
//!
//! The C header (`include/ratify.h`) is generated by cbindgen and committed so
//! consumers do not need the Rust toolchain to use the pre-built artifacts.
//!
//! ## Two verify paths
//!
//! - `ratify_verify_bundle` — simple path: scope + clock override.
//! - `ratify_verify_bundle_opts` — full path: revocation, geo/speed/amount/rate
//!   constraints, session-context binding, stream-context binding.
//!
//! ## Memory model
//!
//! Every function returning a heap-allocated object returns an opaque pointer.
//! Free it with the matching `ratify_*_free`. NULL is always safe to pass to
//! free functions. Double-free is undefined behaviour; the library does not
//! guard against it.
//!
//! ## Error handling
//!
//! Fallible functions write a heap-allocated, null-terminated UTF-8 string to
//! `*err_out` when `err_out` is non-NULL. Always free with `ratify_error_free`.
//! The returned `RatifyStatus` is authoritative; `err_out` carries detail only.
//!
//! ## Thread safety
//!
//! All functions are stateless and re-entrant. The library holds no global
//! mutable state. Concurrent calls from different threads are safe provided
//! each thread owns its own handles. The revocation and rate-counter callbacks
//! you supply must themselves be thread-safe if you call from multiple threads.
//!
//! ## Fixed-size buffers
//!
//! Several fields (`challenge`, `session_context`, `stream_id`) are exactly
//! 32 bytes — a protocol invariant (SPEC §6). Every pointer to such a field
//! is accompanied by a `*_len: usize` parameter or field. Pass the exact byte
//! count; the library returns `RatifyErrBadArgument` if the count is wrong.

#![allow(clippy::missing_safety_doc)]
#![allow(deprecated)] // VerifyOptions.is_revoked is deprecated; we use revocation provider

pub mod advanced;
pub use advanced::*;

// ============================================================================
// Custom entropy source (for embedded targets without OS RNG)
// ============================================================================
// When compiled with feature = "custom-entropy", the getrandom crate will
// call ratify_custom_getrandom() to obtain random bytes instead of using
// the OS entropy source. The application MUST call ratify_set_entropy_source()
// before any call to ratify_challenge_generate() or ratify_delegation_issue().
// See README.md for the full embedded entropy setup guide.
#[cfg(feature = "custom-entropy")]
mod entropy {
    use std::sync::atomic::{AtomicUsize, Ordering};

    static ENTROPY_FN: AtomicUsize = AtomicUsize::new(0);

    /// Register a custom entropy callback for platforms without OS-level RNG.
    ///
    /// `callback` must:
    /// - Write exactly `len` cryptographically random bytes to `buf`.
    /// - Return 0 on success, non-zero if insufficient entropy is available
    ///   (the library will panic rather than use weak randomness).
    /// - Be thread-safe if `ratify_*` functions are called from multiple threads.
    ///
    /// Call this once at startup, before any delegation or challenge operation.
    /// On FreeRTOS with an STM32 TRNG:
    ///   ```c
    ///   int my_entropy(uint8_t *buf, size_t len) {
    ///       for (size_t i = 0; i < len; i += 4) {
    ///           uint32_t rnd;
    ///           if (HAL_RNG_GenerateRandomNumber(&hrng, &rnd) != HAL_OK) return -1;
    ///           memcpy(buf + i, &rnd, (len - i < 4) ? len - i : 4);
    ///       }
    ///       return 0;
    ///   }
    ///   ratify_set_entropy_source(my_entropy);
    ///   ```
    #[no_mangle]
    pub extern "C" fn ratify_set_entropy_source(
        callback: unsafe extern "C" fn(buf: *mut u8, len: usize) -> i32,
    ) {
        ENTROPY_FN.store(callback as usize, Ordering::SeqCst);
    }

    /// Called by getrandom when feature = "custom-entropy" is enabled.
    /// Dispatches to the registered callback or panics if none is registered.
    pub fn custom_getrandom(buf: &mut [u8]) -> Result<(), getrandom::Error> {
        let fn_ptr = ENTROPY_FN.load(Ordering::SeqCst);
        if fn_ptr == 0 {
            panic!(
                "ratify: no entropy source registered. \
                 Call ratify_set_entropy_source() before generating challenges or certs. \
                 See README.md §Custom Entropy."
            );
        }
        let f: unsafe extern "C" fn(*mut u8, usize) -> i32 =
            unsafe { std::mem::transmute(fn_ptr) };
        let result = unsafe { f(buf.as_mut_ptr(), buf.len()) };
        if result == 0 {
            Ok(())
        } else {
            Err(getrandom::Error::UNSUPPORTED)
        }
    }

    // Register our custom_getrandom as the getrandom backend.
    getrandom::register_custom_getrandom!(custom_getrandom);
}

use std::ffi::{CStr, CString};
use std::marker::PhantomData;
use std::os::raw::{c_char, c_double, c_int, c_uchar};
use std::slice;

use ratify_protocol::{
    generate_agent, generate_challenge, generate_human_root, issue_delegation, sign_challenge,
    verify_bundle, AgentIdentity, DelegationCert, HumanRoot, HybridPrivateKey, HybridSignature,
    ProofBundle, RevocationProvider, VerifierContext, VerifyOptions, VerifyResult,
};

// ============================================================================
// Status codes
// ============================================================================

/// Return codes for all fallible Ratify C API functions.
///
/// Values 0–7 are reserved for the current version. A C `switch` must include
/// a `default` case; future versions may add values.
#[repr(C)]
#[derive(Debug, PartialEq, Clone, Copy)]
pub enum RatifyStatus {
    /// Operation succeeded.
    RatifyOk = 0,
    /// A required pointer argument was NULL.
    RatifyErrNullPointer = 1,
    /// JSON parsing or serialisation failed.
    RatifyErrJson = 2,
    /// Cryptographic operation failed (bad key material, invalid signature,
    /// or entropy unavailable).
    RatifyErrCrypto = 3,
    /// A size argument was invalid (e.g., `buf_len` != 32 for a 32-byte field).
    RatifyErrBadArgument = 4,
    /// An internal error that should not occur in normal operation.
    RatifyErrInternal = 5,
    /// A required argument contained invalid UTF-8.
    RatifyErrEncoding = 6,
}

// ============================================================================
// Callback function types (documented here; inlined in structs for cbindgen)
// ============================================================================
//
// RatifyRevocationFn: unsafe extern "C" fn(*const c_char, *mut c_void) -> c_int
//   cert_id — null-terminated hex string of the cert being checked
//   userdata — opaque pointer from RatifyVerifyOptions.revocation_userdata
//   Returns: 1=revoked, 0=not revoked, -1=lookup error (fail-closed → invalid)
//
// RatifyRateCountFn: unsafe extern "C" fn(*const c_char, i64, *mut c_void) -> i64
//   cert_id  — null-terminated hex string
//   window_s — rolling window in seconds
//   userdata — opaque pointer from RatifyVerifierContext.rate_userdata
//   Returns: number of invocations of cert_id in the last window_s seconds

// ============================================================================
// VerifierContext — constraint evaluation inputs
// ============================================================================

/// Application-supplied inputs for evaluating first-class constraints.
///
/// Zero-initialise (`{0}` in C99) all fields you do not use. The verifier
/// fails closed with `constraint_unverifiable` when a required field is absent.
///
/// ```c
/// RatifyVerifierContext ctx = {0};
/// ctx.current_lat  = 47.6062;
/// ctx.current_lon  = -122.3321;
/// ctx.has_location = 1;
/// ```
#[repr(C)]
pub struct RatifyVerifierContext {
    // --- Geo (required by geo_circle, geo_polygon, geo_bbox) ---
    pub current_lat: c_double,
    pub current_lon: c_double,
    pub current_alt_m: c_double,
    /// 1 if the geo fields above are populated, 0 to skip geo evaluation.
    pub has_location: c_int,

    // --- Speed (required by max_speed_mps) ---
    pub current_speed_mps: c_double,
    /// 1 if speed is populated.
    pub has_speed: c_int,

    // --- Transaction amount (required by max_amount) ---
    pub requested_amount: c_double,
    /// Null-terminated ISO 4217 currency code (e.g. "USD"). NULL = no amount.
    pub requested_currency: *const c_char,
    /// 1 if amount fields are populated.
    pub has_amount: c_int,

    // --- Rate counter (required by max_rate) ---
    /// Returns how many times `cert_id` was exercised in the last `window_s`
    /// seconds. NULL = skip rate evaluation (constraint fails closed).
    /// The `cert_id` pointer is only valid for the duration of the callback.
    pub rate_fn: Option<unsafe extern "C" fn(
        cert_id: *const c_char,
        window_s: i64,
        userdata: *mut std::ffi::c_void,
    ) -> i64>,
    /// Passed back to `rate_fn`.
    pub rate_userdata: *mut std::ffi::c_void,
}

// ============================================================================
// Stream context
// ============================================================================

/// Verifier-tracked stream context for v1.1 stream-bound bundles.
///
/// Required when the bundle carries `stream_id` and `stream_seq`. Set
/// `last_seen_seq = 0` for the first turn (no prior accepted turn).
///
/// `stream_id` MUST point to exactly 32 bytes; `stream_id_len` MUST be 32.
/// Any other value returns `RatifyErrBadArgument`.
#[repr(C)]
pub struct RatifyStreamContext {
    /// Pointer to exactly 32 bytes of stream ID.
    pub stream_id: *const c_uchar,
    /// Must be exactly 32. Validated at runtime.
    pub stream_id_len: usize,
    /// Highest sequence number already accepted for this stream (0 = first turn).
    pub last_seen_seq: i64,
}

// ============================================================================
// Full verify options
// ============================================================================

/// Full verification options for `ratify_verify_bundle_opts`.
///
/// Zero-initialise (`{0}`) unused fields.
///
/// ```c
/// RatifyVerifyOptions opts = {0};
/// opts.required_scope      = "meeting:attend";
/// opts.revocation_fn       = my_revocation_callback;
/// opts.revocation_userdata = my_db_handle;
/// // Session binding: opts.session_context + opts.session_context_len = 32
/// ```
#[repr(C)]
pub struct RatifyVerifyOptions {
    /// Scope the bundle must include. NULL or empty string = no scope check.
    pub required_scope: *const c_char,

    /// Fixed Unix timestamp (seconds) for expiry and freshness checks.
    /// 0 = use the system clock. Pass `(int64_t)time(NULL)` for current time.
    /// Note: timestamp 0 (Unix epoch, 1970-01-01) is interpreted as "system clock",
    /// not as the literal year 1970. Embedded systems without a synchronised RTC
    /// should set this explicitly from their best available clock source.
    pub now_unix: i64,

    /// Pointer to `session_context_len` bytes of session context for v1.1
    /// session binding. NULL = no session binding.
    /// When set, `session_context_len` MUST be exactly 32.
    pub session_context: *const c_uchar,
    /// Must be 0 (no session binding) or 32. Any other value returns
    /// `RatifyErrBadArgument`.
    pub session_context_len: usize,

    /// Revocation callback. NULL = no revocation check (unsafe without RevocationProvider).
    /// Signature: int fn(const char *cert_id, void *userdata)
    /// Returns:  1 = revoked (bundle rejected),
    ///           0 = not revoked (verification continues),
    ///          -1 = lookup error (bundle rejected with identity_status=invalid, fail-closed).
    pub revocation_fn: Option<unsafe extern "C" fn(
        cert_id: *const c_char,
        userdata: *mut std::ffi::c_void,
    ) -> c_int>,
    /// Passed back to every `revocation_fn` call.
    pub revocation_userdata: *mut std::ffi::c_void,

    /// Constraint evaluation inputs. NULL = no constraint context; any cert
    /// bearing a geo/speed/amount/rate constraint will fail closed.
    pub context: *const RatifyVerifierContext,

    /// Stream context for v1.1 stream-bound bundles. NULL = no stream validation.
    pub stream: *const RatifyStreamContext,
}

// ============================================================================
// Opaque handle types
// ============================================================================

pub struct RatifyHumanRoot(HumanRoot, HybridPrivateKey);
pub struct RatifyAgent(AgentIdentity, HybridPrivateKey);
pub struct RatifyDelegationCert(DelegationCert);
pub struct RatifyProofBundle(ProofBundle);
pub struct RatifyVerifyResult(pub(crate) VerifyResult);

// ============================================================================
// Internal helpers
// ============================================================================

/// Write a sanitised (null-byte–safe) error message to `*err_out`.
fn set_err(err_out: *mut *mut c_char, msg: &str) {
    if err_out.is_null() { return; }
    // Replace interior null bytes so CString::new never fails on msg content.
    let safe = msg.replace('\0', "<NUL>");
    if let Ok(cs) = CString::new(safe) {
        unsafe { *err_out = cs.into_raw() };
    }
}

/// Convert a null-terminated C string to an owned `String`.
/// Returns an error (via `err_out`) and `None` if the pointer is null or if the
/// string is not valid UTF-8 — never silently degrades.
unsafe fn cstr_to_string(ptr: *const c_char, name: &str, err_out: *mut *mut c_char) -> Option<String> {
    if ptr.is_null() {
        set_err(err_out, &format!("{name} is null"));
        return None;
    }
    match CStr::from_ptr(ptr).to_str() {
        Ok(s) => Some(s.to_owned()),
        Err(_) => {
            set_err(err_out, &format!("{name} contains invalid UTF-8"));
            None
        }
    }
}

/// Allocate a new C string. Returns null if `s` contains interior null bytes
/// (SDK output should never have them, but we guard defensively).
fn new_cstring(s: &str) -> *mut c_char {
    // Replace any unlikely interior nulls rather than silently returning null.
    let safe = s.replace('\0', "<NUL>");
    CString::new(safe).map(|cs| cs.into_raw()).unwrap_or(std::ptr::null_mut())
}


/// Generate a UUID v4 using cryptographically secure entropy.
/// Panics if the system's entropy source is unavailable — this indicates
/// a non-functional environment where no security primitive can operate safely.
fn make_uuid() -> String {
    let mut b = [0u8; 16];
    getrandom::getrandom(&mut b)
        .expect("getrandom: entropy source unavailable — cannot generate secure UUID");
    // RFC 4122 version 4 bit-stamping
    b[6] = (b[6] & 0x0f) | 0x40;
    b[8] = (b[8] & 0x3f) | 0x80;
    // Stack-allocated hex encoding — no heap allocation
    let mut buf = [0u8; 37]; // 36 chars + null terminator
    let hex = b"0123456789abcdef";
    let groups: [&[u8]; 5] = [&b[0..4], &b[4..6], &b[6..8], &b[8..10], &b[10..16]];
    let mut pos = 0;
    for (gi, group) in groups.iter().enumerate() {
        for byte in *group {
            buf[pos]     = hex[(byte >> 4) as usize];
            buf[pos + 1] = hex[(byte & 0xf) as usize];
            pos += 2;
        }
        if gi < 4 { buf[pos] = b'-'; pos += 1; }
    }
    // Safe: we only wrote valid ASCII into buf[0..36]
    std::str::from_utf8(&buf[..36]).unwrap().to_owned()
}

// ============================================================================
// Revocation provider wrapping a C callback
// ============================================================================

struct CRevocationProvider {
    fn_ptr: unsafe extern "C" fn(*const c_char, *mut std::ffi::c_void) -> c_int,
    userdata: *mut std::ffi::c_void,
    // Prevent this struct from being sent across threads automatically.
    // The caller is responsible for ensuring thread safety of the callback.
    _no_sync: PhantomData<*mut ()>,
}

// SAFETY: We allow Send but not Sync. The revocation callback is only called
// synchronously from within verify_bundle — it never escapes that call. If
// the caller ensures the callback and userdata are safe to move to another
// thread (which is true for all stateless C callbacks), Send is sound.
// We do NOT implement Sync, preventing concurrent shared access.
unsafe impl Send for CRevocationProvider {}

impl RevocationProvider for CRevocationProvider {
    fn is_revoked(&self, cert_id: &str) -> Result<bool, String> {
        let cert_id_c = CString::new(cert_id)
            .map_err(|e| format!("cert_id has interior null: {e}"))?;
        // SAFETY: fn_ptr is a valid C function pointer supplied by the caller.
        // userdata lifetime: the caller guarantees it is valid for the duration
        // of verify_bundle_opts (documented in RatifyVerifyOptions).
        let result = unsafe { (self.fn_ptr)(cert_id_c.as_ptr(), self.userdata) };
        match result {
            1  => Ok(true),
            0  => Ok(false),
            n  => Err(format!("revocation callback returned error ({n}) for cert {cert_id}")),
        }
    }
}

// ============================================================================
// Build VerifyOptions from C structs
// ============================================================================

/// Build a Rust `VerifyOptions` from the C option fields.
/// All pointer validation and length checking is done before calling this.
///
/// # Safety
/// The caller must have already validated:
/// - `required_scope` is null or a valid null-terminated UTF-8 string
/// - `session_context` is null or points to exactly `session_context_len` bytes
/// - `stream_id` is null or points to exactly `stream_id_len` bytes
/// - All pointers remain valid for the duration of the returned `VerifyOptions`
unsafe fn build_opts<'a>(
    required_scope: *const c_char,
    now_unix: i64,
    session_context_ptr: *const c_uchar,
    session_context_len: usize,
    revocation_fn: Option<unsafe extern "C" fn(*const c_char, *mut std::ffi::c_void) -> c_int>,
    revocation_userdata: *mut std::ffi::c_void,
    context_ptr: *const RatifyVerifierContext,
    stream_ptr: *const RatifyStreamContext,
) -> VerifyOptions<'a> {
    let scope = if required_scope.is_null() {
        String::new()
    } else {
        CStr::from_ptr(required_scope).to_str().unwrap_or("").to_owned()
    };

    let session_context = if session_context_ptr.is_null() || session_context_len == 0 {
        vec![]
    } else {
        slice::from_raw_parts(session_context_ptr, session_context_len).to_vec()
    };

    let revocation: Option<Box<dyn RevocationProvider + 'a>> = revocation_fn.map(|fn_ptr| {
        Box::new(CRevocationProvider {
            fn_ptr,
            userdata: revocation_userdata,
            _no_sync: PhantomData,
        }) as Box<dyn RevocationProvider + 'a>
    });

    let context = if context_ptr.is_null() {
        VerifierContext::default()
    } else {
        let ctx = &*context_ptr;
        let currency = if ctx.requested_currency.is_null() {
            None
        } else {
            CStr::from_ptr(ctx.requested_currency).to_str().ok().map(|s| s.to_owned())
        };

        let rate_fn: Option<unsafe extern "C" fn(*const c_char, i64, *mut std::ffi::c_void) -> i64> = ctx.rate_fn;
        let rate_ud = ctx.rate_userdata;
        let invocations: Option<Box<dyn Fn(&str, i64) -> i64 + 'a>> = rate_fn.map(|f| {
            Box::new(move |cert_id: &str, window_s: i64| -> i64 {
                // cert_id is stack-allocated; the closure must not store the pointer.
                if let Ok(c) = CString::new(cert_id) {
                    f(c.as_ptr(), window_s, rate_ud)
                } else {
                    0
                }
            }) as Box<dyn Fn(&str, i64) -> i64 + 'a>
        });

        VerifierContext {
            current_lat:           if ctx.has_location != 0 { Some(ctx.current_lat) } else { None },
            current_lon:           if ctx.has_location != 0 { Some(ctx.current_lon) } else { None },
            current_alt_m:         if ctx.has_location != 0 { Some(ctx.current_alt_m) } else { None },
            current_speed_mps:     if ctx.has_speed    != 0 { Some(ctx.current_speed_mps) } else { None },
            requested_amount:      if ctx.has_amount   != 0 { Some(ctx.requested_amount) } else { None },
            requested_currency:    if ctx.has_amount   != 0 { currency } else { None },
            invocations_in_window: invocations,
        }
    };

    let stream = if stream_ptr.is_null() {
        None
    } else {
        let s = &*stream_ptr;
        if s.stream_id.is_null() || s.stream_id_len == 0 {
            None
        } else {
            let id = slice::from_raw_parts(s.stream_id, s.stream_id_len).to_vec();
            Some(ratify_protocol::StreamContext {
                stream_id: id,
                last_seen_seq: s.last_seen_seq,
            })
        }
    };

    VerifyOptions {
        required_scope: scope,
        revocation,
        now: if now_unix == 0 { None } else { Some(now_unix) },
        session_context,
        context,
        stream,
        is_revoked: None,
        ..VerifyOptions::default()
    }
}

// ============================================================================
// Key generation (infallible in the Rust SDK)
// ============================================================================

/// Generate a new HumanRoot keypair (the delegating principal).
///
/// The handle contains both the public identity and the private signing key.
/// Free with `ratify_human_root_free`.
///
/// # Panics
/// On embedded targets where the entropy source is unavailable. This indicates
/// a non-functional system; no security operation is possible.
#[no_mangle]
pub unsafe extern "C" fn ratify_human_root_generate(
    out: *mut *mut RatifyHumanRoot,
) -> RatifyStatus {
    if out.is_null() { return RatifyStatus::RatifyErrNullPointer; }
    let (root, priv_key) = generate_human_root();
    *out = Box::into_raw(Box::new(RatifyHumanRoot(root, priv_key)));
    RatifyStatus::RatifyOk
}

/// Free a `RatifyHumanRoot` handle. Safe to call with NULL.
#[no_mangle]
pub unsafe extern "C" fn ratify_human_root_free(handle: *mut RatifyHumanRoot) {
    if !handle.is_null() { drop(Box::from_raw(handle)); }
}

/// Serialise the HumanRoot public identity to JSON (no private key material).
/// Free the returned string with `ratify_string_free`.
#[no_mangle]
pub unsafe extern "C" fn ratify_human_root_to_json(
    handle: *const RatifyHumanRoot,
    err_out: *mut *mut c_char,
) -> *mut c_char {
    if handle.is_null() { set_err(err_out, "handle is null"); return std::ptr::null_mut(); }
    match serde_json::to_string(&(*handle).0) {
        Ok(s) => new_cstring(&s),
        Err(e) => { set_err(err_out, &e.to_string()); std::ptr::null_mut() }
    }
}

/// Return the human root's 32-hex-character ID. Free with `ratify_string_free`.
#[no_mangle]
pub unsafe extern "C" fn ratify_human_root_id(
    handle: *const RatifyHumanRoot,
) -> *mut c_char {
    if handle.is_null() { return std::ptr::null_mut(); }
    new_cstring(&(*handle).0.id)
}

/// Return the human root's public key as JSON (`{"ed25519":"...","ml_dsa_65":"..."}`).
/// This is the verifier public key for revocation list / push / witness verification.
/// Free with `ratify_string_free`.
#[no_mangle]
pub unsafe extern "C" fn ratify_human_root_pub_key_json(
    handle: *const RatifyHumanRoot,
    err_out: *mut *mut c_char,
) -> *mut c_char {
    if handle.is_null() { set_err(err_out, "handle is null"); return std::ptr::null_mut(); }
    match serde_json::to_string(&(*handle).0.public_key) {
        Ok(s) => new_cstring(&s),
        Err(e) => { set_err(err_out, &e.to_string()); std::ptr::null_mut() }
    }
}

/// Generate a new AgentIdentity keypair.
///
/// - `name_utf8` — the agent's human-readable name (null-terminated UTF-8).
/// - `agent_type_utf8` — e.g. `"meeting_bot"`, `"drone"`, `"mcp_server"`, `"custom"`.
///
/// Free with `ratify_agent_free`.
#[no_mangle]
pub unsafe extern "C" fn ratify_agent_generate(
    name_utf8: *const c_char,
    agent_type_utf8: *const c_char,
    out: *mut *mut RatifyAgent,
) -> RatifyStatus {
    if name_utf8.is_null() || agent_type_utf8.is_null() || out.is_null() {
        return RatifyStatus::RatifyErrNullPointer;
    }
    let name = match CStr::from_ptr(name_utf8).to_str() {
        Ok(s) => s,
        Err(_) => return RatifyStatus::RatifyErrEncoding,
    };
    let agent_type = match CStr::from_ptr(agent_type_utf8).to_str() {
        Ok(s) => s,
        Err(_) => return RatifyStatus::RatifyErrEncoding,
    };
    let (identity, priv_key) = generate_agent(name, agent_type);
    *out = Box::into_raw(Box::new(RatifyAgent(identity, priv_key)));
    RatifyStatus::RatifyOk
}

/// Free a `RatifyAgent` handle. Safe to call with NULL.
#[no_mangle]
pub unsafe extern "C" fn ratify_agent_free(handle: *mut RatifyAgent) {
    if !handle.is_null() { drop(Box::from_raw(handle)); }
}

/// Return the agent's 32-hex-character ID. Free with `ratify_string_free`.
#[no_mangle]
pub unsafe extern "C" fn ratify_agent_id(
    handle: *const RatifyAgent,
) -> *mut c_char {
    if handle.is_null() { return std::ptr::null_mut(); }
    new_cstring(&(*handle).0.id)
}

// ============================================================================
// Delegation (infallible signing in the Rust SDK)
// ============================================================================

/// Issue a DelegationCert from a HumanRoot to an Agent.
///
/// - `scopes_json` — JSON array of scope strings, e.g. `["meeting:attend"]`.
/// - `issued_at_unix` — Unix timestamp for `issued_at`. Pass 0 to use the
///   system clock. Embedded targets without a synchronised RTC should set this
///   explicitly (e.g. from an NTP-synced value stored in flash).
/// - `expires_at_unix` — Unix timestamp for expiry. Pass 0 for no expiry:
///   the library signs NO_EXPIRY_SENTINEL (4070908799), which means
///   "no expiry (until revoked)" per SPEC §5.7 — display and policy code
///   MUST NOT treat it as a literal 2099 expiry. See
///   `ratify_no_expiry_sentinel()` / `ratify_expires_at_is_no_expiry()`.
///
/// Free with `ratify_delegation_cert_free`.
#[no_mangle]
pub unsafe extern "C" fn ratify_delegation_issue(
    issuer: *const RatifyHumanRoot,
    subject: *const RatifyAgent,
    scopes_json: *const c_char,
    issued_at_unix: i64,
    expires_at_unix: i64,
    out: *mut *mut RatifyDelegationCert,
    err_out: *mut *mut c_char,
) -> RatifyStatus {
    if issuer.is_null() || subject.is_null() || scopes_json.is_null() || out.is_null() {
        set_err(err_out, "null argument");
        return RatifyStatus::RatifyErrNullPointer;
    }
    let scopes_str = match cstr_to_string(scopes_json, "scopes_json", err_out) {
        Some(s) => s, None => return RatifyStatus::RatifyErrJson,
    };
    let scopes: Vec<String> = match serde_json::from_str(&scopes_str) {
        Ok(v) => v,
        Err(e) => { set_err(err_out, &format!("scopes_json: {e}")); return RatifyStatus::RatifyErrJson; }
    };

    let issued_at = if issued_at_unix == 0 {
        std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .map(|d| d.as_secs() as i64)
            .unwrap_or(0)
    } else {
        issued_at_unix
    };
    let expires_at = if expires_at_unix == 0 { ratify_protocol::NO_EXPIRY_SENTINEL } else { expires_at_unix };

    let cert_id = make_uuid(); // panics on entropy failure
    let issuer_ref = &*issuer;
    let subject_ref = &*subject;

    let mut cert = DelegationCert {
        cert_id,
        version: 1,
        issuer_id: issuer_ref.0.id.clone(),
        issuer_pub_key: issuer_ref.0.public_key.clone(),
        subject_id: subject_ref.0.id.clone(),
        subject_pub_key: subject_ref.0.public_key.clone(),
        scope: scopes,
        constraints: vec![],
        issued_at,
        expires_at,
        // Zero placeholder — overwritten by issue_delegation below.
        signature: HybridSignature { ed25519: vec![0u8; 64], ml_dsa_65: vec![0u8; 3309] },
    };

    // issue_delegation is documented infallible in the Rust SDK; the signature
    // field is fully overwritten before we box the cert.
    issue_delegation(&mut cert, &issuer_ref.1);

    *out = Box::into_raw(Box::new(RatifyDelegationCert(cert)));
    RatifyStatus::RatifyOk
}

/// Serialise a DelegationCert to JSON. Free with `ratify_string_free`.
#[no_mangle]
pub unsafe extern "C" fn ratify_delegation_cert_to_json(
    handle: *const RatifyDelegationCert,
    err_out: *mut *mut c_char,
) -> *mut c_char {
    if handle.is_null() { set_err(err_out, "handle is null"); return std::ptr::null_mut(); }
    match serde_json::to_string(&(*handle).0) {
        Ok(s) => new_cstring(&s),
        Err(e) => { set_err(err_out, &e.to_string()); std::ptr::null_mut() }
    }
}

/// Free a `RatifyDelegationCert` handle. Safe to call with NULL.
#[no_mangle]
pub unsafe extern "C" fn ratify_delegation_cert_free(handle: *mut RatifyDelegationCert) {
    if !handle.is_null() { drop(Box::from_raw(handle)); }
}

// ============================================================================
// Challenge and ProofBundle
// ============================================================================

/// Generate a fresh 32-byte cryptographic challenge.
///
/// `buf` must point to at least `buf_len` bytes of writable memory.
/// `buf_len` must be exactly 32; any other value returns `RatifyErrBadArgument`.
///
/// Returns `RatifyErrCrypto` if the system's entropy source is unavailable.
#[no_mangle]
pub unsafe extern "C" fn ratify_challenge_generate(
    buf: *mut c_uchar,
    buf_len: usize,
) -> RatifyStatus {
    if buf.is_null() { return RatifyStatus::RatifyErrNullPointer; }
    if buf_len != 32 { return RatifyStatus::RatifyErrBadArgument; }
    let bytes = generate_challenge();
    if bytes.len() < 32 { return RatifyStatus::RatifyErrCrypto; }
    slice::from_raw_parts_mut(buf, 32).copy_from_slice(&bytes[..32]);
    RatifyStatus::RatifyOk
}

/// Build a ProofBundle: the agent signs a fresh challenge with its delegation cert.
///
/// - `agent` — the Agent handle (owns the signing key).
/// - `cert_json` — delegation cert JSON from `ratify_delegation_cert_to_json`.
/// - `challenge` — pointer to exactly `challenge_len` bytes of challenge data
///   (typically 32). `challenge_len` must be 32.
/// - `challenge_at_unix` — Unix timestamp when the challenge was generated.
///   Pass `(int64_t)time(NULL)` for the current time. Must not be 0 on
///   systems where time(NULL) could legitimately return 0 — use an explicit value.
///
/// Free with `ratify_proof_bundle_free`.
#[no_mangle]
pub unsafe extern "C" fn ratify_proof_bundle_create(
    agent: *const RatifyAgent,
    cert_json: *const c_char,
    challenge: *const c_uchar,
    challenge_len: usize,
    challenge_at_unix: i64,
    out: *mut *mut RatifyProofBundle,
    err_out: *mut *mut c_char,
) -> RatifyStatus {
    if agent.is_null() || cert_json.is_null() || challenge.is_null() || out.is_null() {
        set_err(err_out, "null argument");
        return RatifyStatus::RatifyErrNullPointer;
    }
    if challenge_len != 32 {
        set_err(err_out, "challenge_len must be exactly 32");
        return RatifyStatus::RatifyErrBadArgument;
    }
    let cert_str = match cstr_to_string(cert_json, "cert_json", err_out) {
        Some(s) => s, None => return RatifyStatus::RatifyErrJson,
    };
    let cert: DelegationCert = match serde_json::from_str(&cert_str) {
        Ok(c) => c,
        Err(e) => { set_err(err_out, &format!("cert_json: {e}")); return RatifyStatus::RatifyErrJson; }
    };

    let challenge_bytes = slice::from_raw_parts(challenge, 32).to_vec();
    let agent_ref = &*agent;
    let sig = sign_challenge(&challenge_bytes, challenge_at_unix, &agent_ref.1);

    let bundle = ProofBundle {
        agent_id: agent_ref.0.id.clone(),
        agent_pub_key: agent_ref.0.public_key.clone(),
        delegations: vec![cert],
        challenge: challenge_bytes,
        challenge_at: challenge_at_unix,
        challenge_sig: sig,
        session_context: vec![],
        stream_id: vec![],
        stream_seq: 0,
    };
    *out = Box::into_raw(Box::new(RatifyProofBundle(bundle)));
    RatifyStatus::RatifyOk
}

/// Serialise a ProofBundle to JSON. Free with `ratify_string_free`.
#[no_mangle]
pub unsafe extern "C" fn ratify_proof_bundle_to_json(
    handle: *const RatifyProofBundle,
    err_out: *mut *mut c_char,
) -> *mut c_char {
    if handle.is_null() { set_err(err_out, "handle is null"); return std::ptr::null_mut(); }
    match serde_json::to_string(&(*handle).0) {
        Ok(s) => new_cstring(&s),
        Err(e) => { set_err(err_out, &e.to_string()); std::ptr::null_mut() }
    }
}

/// Free a `RatifyProofBundle` handle. Safe to call with NULL.
#[no_mangle]
pub unsafe extern "C" fn ratify_proof_bundle_free(handle: *mut RatifyProofBundle) {
    if !handle.is_null() { drop(Box::from_raw(handle)); }
}

// ============================================================================
// Verification — simple path
// ============================================================================

/// Verify a ProofBundle JSON string — simple path (scope + clock only).
///
/// Use for production embedded verifiers that need only scope enforcement and
/// a fixed clock. Use `ratify_verify_bundle_opts` for revocation callbacks,
/// constraint context, session binding, or stream binding.
///
/// - `bundle_json` — null-terminated JSON ProofBundle string.
/// - `required_scope` — null-terminated scope to require. NULL = no scope check.
/// - `now_unix` — Unix timestamp for expiry/freshness. 0 = system clock.
///   Note: 0 is treated as "use system clock", not epoch year 1970.
///
/// Returns `RatifyOk` whether or not the bundle is cryptographically valid.
/// Inspect with `ratify_verify_result_is_valid`. Free with `ratify_verify_result_free`.
#[no_mangle]
pub unsafe extern "C" fn ratify_verify_bundle(
    bundle_json: *const c_char,
    required_scope: *const c_char,
    now_unix: i64,
    out: *mut *mut RatifyVerifyResult,
    err_out: *mut *mut c_char,
) -> RatifyStatus {
    // Validate required_scope is valid UTF-8 before delegating, so the error
    // is surfaced immediately rather than silently becoming an empty scope.
    if !required_scope.is_null() {
        if CStr::from_ptr(required_scope).to_str().is_err() {
            set_err(err_out, "required_scope contains invalid UTF-8");
            return RatifyStatus::RatifyErrEncoding;
        }
    }
    ratify_verify_bundle_opts(
        bundle_json,
        &RatifyVerifyOptions {
            required_scope,
            now_unix,
            session_context: std::ptr::null(),
            session_context_len: 0,
            revocation_fn: None,
            revocation_userdata: std::ptr::null_mut(),
            context: std::ptr::null(),
            stream: std::ptr::null(),
        },
        out,
        err_out,
    )
}

// ============================================================================
// Verification — full options path
// ============================================================================

/// Verify a ProofBundle JSON string with the full option set.
///
/// `opts` may be NULL, which is equivalent to `ratify_verify_bundle` with
/// no scope, system clock, and no additional options.
///
/// Returns `RatifyErrBadArgument` if `session_context_len` is not 0 or 32,
/// or if `stream_id_len` is not 0 or 32.
#[no_mangle]
pub unsafe extern "C" fn ratify_verify_bundle_opts(
    bundle_json: *const c_char,
    opts: *const RatifyVerifyOptions,
    out: *mut *mut RatifyVerifyResult,
    err_out: *mut *mut c_char,
) -> RatifyStatus {
    if bundle_json.is_null() || out.is_null() {
        set_err(err_out, "bundle_json and out must be non-null");
        return RatifyStatus::RatifyErrNullPointer;
    }

    // Validate before any allocation.
    if !opts.is_null() {
        let o = &*opts;

        // session_context_len must be 0 or exactly 32
        if o.session_context_len != 0 && o.session_context_len != 32 {
            set_err(err_out, "session_context_len must be 0 or 32");
            return RatifyStatus::RatifyErrBadArgument;
        }
        if o.session_context_len == 32 && o.session_context.is_null() {
            set_err(err_out, "session_context is null but session_context_len is 32");
            return RatifyStatus::RatifyErrNullPointer;
        }

        // Validate stream context if present
        if !o.stream.is_null() {
            let s = &*o.stream;
            if s.stream_id_len != 0 && s.stream_id_len != 32 {
                set_err(err_out, "stream_id_len must be 0 or 32");
                return RatifyStatus::RatifyErrBadArgument;
            }
            if s.stream_id_len == 32 && s.stream_id.is_null() {
                set_err(err_out, "stream_id is null but stream_id_len is 32");
                return RatifyStatus::RatifyErrNullPointer;
            }
        }

        // Validate required_scope UTF-8
        if !o.required_scope.is_null() {
            if CStr::from_ptr(o.required_scope).to_str().is_err() {
                set_err(err_out, "required_scope contains invalid UTF-8");
                return RatifyStatus::RatifyErrEncoding;
            }
        }
    }

    let bundle_str = match cstr_to_string(bundle_json, "bundle_json", err_out) {
        Some(s) => s, None => return RatifyStatus::RatifyErrJson,
    };
    let bundle: ProofBundle = match serde_json::from_str(&bundle_str) {
        Ok(b) => b,
        Err(e) => { set_err(err_out, &format!("bundle_json: {e}")); return RatifyStatus::RatifyErrJson; }
    };

    let rust_opts = if opts.is_null() {
        VerifyOptions::default()
    } else {
        let o = &*opts;
        build_opts(
            o.required_scope,
            o.now_unix,
            o.session_context,
            o.session_context_len,
            o.revocation_fn,
            o.revocation_userdata,
            o.context,
            o.stream,
        )
    };

    let result = verify_bundle(&bundle, &rust_opts);
    *out = Box::into_raw(Box::new(RatifyVerifyResult(result)));
    RatifyStatus::RatifyOk
}

// ============================================================================
// VerifyResult accessors
// ============================================================================

/// Returns 1 if the verification result is valid, 0 if invalid or handle is NULL.
#[no_mangle]
pub unsafe extern "C" fn ratify_verify_result_is_valid(
    handle: *const RatifyVerifyResult,
) -> c_int {
    if handle.is_null() { return 0; }
    (*handle).0.valid as c_int
}

/// Returns the `identity_status` string (e.g. `"authorized_agent"`, `"revoked"`).
///
/// For well-known status values this returns a pointer to a static string —
/// do NOT free it with `ratify_string_free`. For unknown values (future SDK
/// versions) it returns a heap-allocated string that MUST be freed.
///
/// In practice: always check `ratify_verify_result_is_valid` first; only call
/// this for logging or diagnostics. To be safe, always call `ratify_string_free`
/// on the result — freeing a static string is a no-op if the pointer is not heap-allocated.
///
/// Wait — static string pointers cannot be freed via `ratify_string_free`. To avoid
/// a double-free if the caller always calls free, this function ALWAYS returns a
/// heap-allocated copy for safety. The static optimisation is used only internally.
#[no_mangle]
pub unsafe extern "C" fn ratify_verify_result_identity_status(
    handle: *const RatifyVerifyResult,
) -> *mut c_char {
    if handle.is_null() { return std::ptr::null_mut(); }
    // Always return a heap copy so the caller can always call ratify_string_free.
    new_cstring((*handle).0.identity_status.as_str())
}

/// Returns the verified `human_id` hex string (32 characters).
/// Empty string if not populated. Free with `ratify_string_free`.
#[no_mangle]
pub unsafe extern "C" fn ratify_verify_result_human_id(
    handle: *const RatifyVerifyResult,
) -> *mut c_char {
    if handle.is_null() { return std::ptr::null_mut(); }
    new_cstring(&(*handle).0.human_id)
}

/// Returns the verified `agent_id` hex string (32 characters).
/// Empty string if not populated. Free with `ratify_string_free`.
#[no_mangle]
pub unsafe extern "C" fn ratify_verify_result_agent_id(
    handle: *const RatifyVerifyResult,
) -> *mut c_char {
    if handle.is_null() { return std::ptr::null_mut(); }
    new_cstring(&(*handle).0.agent_id)
}

/// Returns the `error_reason` detail string when verification failed.
/// Empty string on success. Free with `ratify_string_free`.
#[no_mangle]
pub unsafe extern "C" fn ratify_verify_result_error_reason(
    handle: *const RatifyVerifyResult,
) -> *mut c_char {
    if handle.is_null() { return std::ptr::null_mut(); }
    new_cstring(&(*handle).0.error_reason)
}

/// Free a `RatifyVerifyResult` handle. Safe to call with NULL.
#[no_mangle]
pub unsafe extern "C" fn ratify_verify_result_free(handle: *mut RatifyVerifyResult) {
    if !handle.is_null() { drop(Box::from_raw(handle)); }
}

// ============================================================================
// String / memory management
// ============================================================================

/// Free a heap-allocated string returned by any `ratify_*` accessor.
/// Safe to call with NULL.
#[no_mangle]
pub unsafe extern "C" fn ratify_string_free(s: *mut c_char) {
    if !s.is_null() { drop(CString::from_raw(s)); }
}

/// Free an error string written to an `err_out` parameter.
/// Safe to call with NULL.
#[no_mangle]
pub unsafe extern "C" fn ratify_error_free(s: *mut c_char) {
    if !s.is_null() { drop(CString::from_raw(s)); }
}

/// Returns the library version string. Statically allocated — do NOT free.
#[no_mangle]
pub extern "C" fn ratify_version() -> *const c_char {
    concat!(env!("CARGO_PKG_VERSION"), "\0").as_ptr() as *const c_char
}

/// Returns NO_EXPIRY_SENTINEL (4070908799 = 2099-12-31 23:59:59 UTC): the
/// `expires_at` value that means "no expiry (until revoked)" per SPEC §5.7.
#[no_mangle]
pub extern "C" fn ratify_no_expiry_sentinel() -> i64 {
    ratify_protocol::NO_EXPIRY_SENTINEL
}

/// Returns true iff `expires_at_unix` is the no-expiry sentinel. Display and
/// policy code MUST branch on this rather than treating the sentinel as a
/// real 2099 timestamp: a sentinel cert is an open-ended grant terminated
/// only by revocation, not a ~75-year grant.
#[no_mangle]
pub extern "C" fn ratify_expires_at_is_no_expiry(expires_at_unix: i64) -> bool {
    expires_at_unix == ratify_protocol::NO_EXPIRY_SENTINEL
}
