// Cross-SDK byte-equivalence corpus consumer.
//
// Loads testvectors/v1/cross_sdk_vectors.json (generated by
// cmd/ratify-testvectors) and asserts that the TypeScript SDK produces
// byte-identical output to the Go reference for every vector:
//
//   - verifier_context_hash (SPEC §17.6)
//   - bundle_hash (SPEC §17.5)
//   - policy_verdict_sign_bytes (SPEC §17.6)
//   - verification_receipt_sign_bytes (SPEC §17.5)
//
// Hub-and-spoke design: Go generates expected bytes, TS/Python/Rust each
// assert against them. Transitively proves all four SDKs are pairwise
// byte-identical without writing N×N assertions.

import { test } from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

import {
  bundleHash,
  decodeProofBundle,
  verifierContextHash,
  policyVerdictSignBytesBuf,
  verificationReceiptSignBytesBuf,
  type PolicyVerdict,
  type VerificationReceipt,
  type VerifierContext,
  hybridKeypairFromSeeds,
  deriveID,
} from "../src/index.js";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const VECTOR_PATH = join(
  __dirname,
  "..",
  "..",
  "..",
  "testvectors",
  "v1",
  "cross_sdk_vectors.json",
);

interface CrossSDKVector {
  kind: string;
  name: string;
  description: string;
  input: Record<string, unknown>;
  expected_hash_hex?: string;
  expected_bytes_b64?: string;
}

interface CrossSDKDoc {
  description: string;
  vectors: CrossSDKVector[];
}

const doc = JSON.parse(readFileSync(VECTOR_PATH, "utf8")) as CrossSDKDoc;

if (!doc.vectors || doc.vectors.length === 0) {
  throw new Error(`No vectors in ${VECTOR_PATH}`);
}

function fromBase64(s: string): Uint8Array {
  return Uint8Array.from(Buffer.from(s, "base64"));
}

function fromHex(s: string): Uint8Array {
  return Uint8Array.from(Buffer.from(s, "hex"));
}

function hex(u: Uint8Array): string {
  return Buffer.from(u).toString("hex");
}

function b64(u: Uint8Array): string {
  return Buffer.from(u).toString("base64");
}

for (const v of doc.vectors) {
  test(`cross-SDK [${v.kind}]: ${v.name}`, async () => {
    switch (v.kind) {
      case "verifier_context_hash": {
        const inp = v.input as Record<string, unknown>;
        // Reconstruct a TS VerifierContext from the canonical input shape.
        // The Has* flags from the fixture are authoritative: when false, the
        // TS implementation derives `has_*` from presence, so the
        // corresponding numeric stays undefined.
        const ctx: VerifierContext = {};
        if (inp.has_location) {
          ctx.current_lat = inp.current_lat as number;
          ctx.current_lon = inp.current_lon as number;
          ctx.current_alt_m = inp.current_alt_m as number;
        }
        if (inp.has_speed) {
          ctx.current_speed_mps = inp.current_speed_mps as number;
        }
        if (inp.has_amount) {
          ctx.requested_amount = inp.requested_amount as number;
          ctx.requested_currency = inp.requested_currency as string;
        }
        const got = hex(verifierContextHash(ctx));
        assert.equal(got, v.expected_hash_hex, v.name);
        break;
      }
      case "bundle_hash": {
        // The input embeds a full canonical ProofBundle; decode it with the
        // public wire codec, hash it, and compare.
        const inp = v.input as Record<string, unknown>;
        const bundle = decodeProofBundle(JSON.stringify(inp.bundle));
        const got = hex(bundleHash(bundle));
        assert.equal(got, v.expected_hash_hex, v.name);
        break;
      }
      case "policy_verdict_sign_bytes": {
        const inp = v.input as Record<string, unknown>;
        const v0: PolicyVerdict = {
          version: inp.version as number,
          verdict_id: inp.verdict_id as string,
          agent_id: inp.agent_id as string,
          scope: inp.scope as string,
          allow: inp.allow as boolean,
          context_hash: fromHex(inp.context_hash_hex as string),
          issued_at: inp.issued_at as number,
          valid_until: inp.valid_until as number,
          mac: new Uint8Array(0),
        };
        const got = b64(policyVerdictSignBytesBuf(v0));
        assert.equal(got, v.expected_bytes_b64, v.name);
        break;
      }
      case "verification_receipt_sign_bytes": {
        const inp = v.input as Record<string, unknown>;
        const vp = inp.verifier_pub as { ed25519: string; ml_dsa_65: string };
        const r: VerificationReceipt = {
          version: inp.version as number,
          verifier_id: inp.verifier_id as string,
          verifier_pub: {
            ed25519: fromBase64(vp.ed25519),
            ml_dsa_65: fromBase64(vp.ml_dsa_65),
          },
          bundle_hash: fromHex(inp.bundle_hash_hex as string),
          decision: inp.decision as any,
          human_id: inp.human_id as string | undefined,
          agent_id: inp.agent_id as string | undefined,
          granted_scope: inp.granted_scope as string[] | undefined,
          error_reason: inp.error_reason as string | undefined,
          verified_at: inp.verified_at as number,
          prev_hash: fromHex(inp.prev_hash_hex as string),
          signature: { ed25519: new Uint8Array(0), ml_dsa_65: new Uint8Array(0) },
        };
        const got = b64(verificationReceiptSignBytesBuf(r));
        assert.equal(got, v.expected_bytes_b64, v.name);
        break;
      }
      default:
        throw new Error(`unknown cross-SDK vector kind: ${v.kind}`);
    }
  });
}

// Deterministic keygen known-answer vector.
//
// The canonical fixtures carry no seeds, so nothing else holds the seeded
// keygen implementations to each other: an SDK could be deterministic and
// deterministically different from the others, and every existing test would
// still pass. Asserted identically in the Go, Rust, and C suites.
//
// Python does not implement seeded keygen (see docs/SDKS.md), so it has no
// counterpart to this test.
test("cross-sdk: hybridKeypairFromSeeds matches the canonical vector", async () => {
  const edSeed = new Uint8Array(32);
  const mlSeed = new Uint8Array(32);
  for (let i = 0; i < 32; i++) {
    edSeed[i] = i;
    mlSeed[i] = (0xa0 + i) & 0xff;
  }

  const { publicKey } = await hybridKeypairFromSeeds(edSeed, mlSeed);
  const hex = (b: Uint8Array) =>
    Array.from(b, (x) => x.toString(16).padStart(2, "0")).join("");

  assert.equal(
    hex(publicKey.ed25519),
    "03a107bff3ce10be1d70dd18e74bc09967e4d6309ba50d5f1ddc8664125531b8",
  );
  assert.equal(publicKey.ml_dsa_65.length, 1952);
  assert.equal(
    hex(publicKey.ml_dsa_65.slice(0, 32)),
    "1963d47ac0e93110e3add0354e0333e31c75de34038909ec8833eb6e2aaa7218",
  );
  assert.equal(deriveID(publicKey), "3823136b5a5fc4c755b22704474172c0");

  // The same seeds must rebuild the same identity: the property the entry
  // exists for, and what lets an issuer persist seeds instead of keys.
  const again = await hybridKeypairFromSeeds(edSeed, mlSeed);
  assert.equal(deriveID(again.publicKey), deriveID(publicKey));
});
