// Cross-SDK byte-equivalence corpus consumer.
//
// Loads testvectors/v1/cross_sdk_vectors.json (generated by
// cmd/ratify-testvectors) and asserts that the TypeScript SDK produces
// byte-identical output to the Go reference for every vector:
//
//   - verifier_context_hash (SPEC §17.6)
//   - bundle_hash (SPEC §17.5)
//   - policy_verdict_sign_bytes (SPEC §17.6)
//   - verification_receipt_sign_bytes (SPEC §17.5)
//
// Hub-and-spoke design: Go generates expected bytes, TS/Python/Rust each
// assert against them. Transitively proves all four SDKs are pairwise
// byte-identical without writing N×N assertions.

import { test } from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

import {
  bundleHash,
  verifierContextHash,
  policyVerdictSignBytesBuf,
  verificationReceiptSignBytesBuf,
  type PolicyVerdict,
  type ProofBundle,
  type VerificationReceipt,
  type VerifierContext,
} from "../src/index.js";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const VECTOR_PATH = join(
  __dirname,
  "..",
  "..",
  "..",
  "testvectors",
  "v1",
  "cross_sdk_vectors.json",
);

interface CrossSDKVector {
  kind: string;
  name: string;
  description: string;
  input: Record<string, unknown>;
  expected_hash_hex?: string;
  expected_bytes_b64?: string;
}

interface CrossSDKDoc {
  description: string;
  vectors: CrossSDKVector[];
}

const doc = JSON.parse(readFileSync(VECTOR_PATH, "utf8")) as CrossSDKDoc;

if (!doc.vectors || doc.vectors.length === 0) {
  throw new Error(`No vectors in ${VECTOR_PATH}`);
}

function fromBase64(s: string): Uint8Array {
  return Uint8Array.from(Buffer.from(s, "base64"));
}

function fromHex(s: string): Uint8Array {
  return Uint8Array.from(Buffer.from(s, "hex"));
}

function hex(u: Uint8Array): string {
  return Buffer.from(u).toString("hex");
}

function b64(u: Uint8Array): string {
  return Buffer.from(u).toString("base64");
}

for (const v of doc.vectors) {
  test(`cross-SDK [${v.kind}]: ${v.name}`, async () => {
    switch (v.kind) {
      case "verifier_context_hash": {
        const inp = v.input as Record<string, unknown>;
        // Reconstruct a TS VerifierContext from the canonical input shape.
        // The Has* flags from the fixture are authoritative: when false, the
        // TS implementation derives `has_*` from presence, so the
        // corresponding numeric stays undefined.
        const ctx: VerifierContext = {};
        if (inp.has_location) {
          ctx.current_lat = inp.current_lat as number;
          ctx.current_lon = inp.current_lon as number;
          ctx.current_alt_m = inp.current_alt_m as number;
        }
        if (inp.has_speed) {
          ctx.current_speed_mps = inp.current_speed_mps as number;
        }
        if (inp.has_amount) {
          ctx.requested_amount = inp.requested_amount as number;
          ctx.requested_currency = inp.requested_currency as string;
        }
        const got = hex(verifierContextHash(ctx));
        assert.equal(got, v.expected_hash_hex, v.name);
        break;
      }
      case "bundle_hash": {
        // The input embeds a full canonical ProofBundle; reconstruct it,
        // hash it, and compare.
        const inp = v.input as Record<string, unknown>;
        const rawBundle = inp.bundle as Record<string, unknown>;
        const bundle: ProofBundle = {
          agent_id: rawBundle.agent_id as string,
          agent_pub_key: {
            ed25519: fromBase64(
              (rawBundle.agent_pub_key as { ed25519: string }).ed25519,
            ),
            ml_dsa_65: fromBase64(
              (rawBundle.agent_pub_key as { ml_dsa_65: string }).ml_dsa_65,
            ),
          },
          delegations: (rawBundle.delegations as Record<string, unknown>[]).map(
            (d) => ({
              cert_id: d.cert_id as string,
              version: d.version as number,
              issuer_id: d.issuer_id as string,
              issuer_pub_key: {
                ed25519: fromBase64(
                  (d.issuer_pub_key as { ed25519: string }).ed25519,
                ),
                ml_dsa_65: fromBase64(
                  (d.issuer_pub_key as { ml_dsa_65: string }).ml_dsa_65,
                ),
              },
              subject_id: d.subject_id as string,
              subject_pub_key: {
                ed25519: fromBase64(
                  (d.subject_pub_key as { ed25519: string }).ed25519,
                ),
                ml_dsa_65: fromBase64(
                  (d.subject_pub_key as { ml_dsa_65: string }).ml_dsa_65,
                ),
              },
              scope: d.scope as string[],
              constraints: (d.constraints ?? []) as any[],
              issued_at: d.issued_at as number,
              expires_at: d.expires_at as number,
              signature: {
                ed25519: fromBase64(
                  (d.signature as { ed25519: string }).ed25519,
                ),
                ml_dsa_65: fromBase64(
                  (d.signature as { ml_dsa_65: string }).ml_dsa_65,
                ),
              },
            }),
          ),
          challenge: fromBase64(rawBundle.challenge as string),
          challenge_at: rawBundle.challenge_at as number,
          challenge_sig: {
            ed25519: fromBase64(
              (rawBundle.challenge_sig as { ed25519: string }).ed25519,
            ),
            ml_dsa_65: fromBase64(
              (rawBundle.challenge_sig as { ml_dsa_65: string }).ml_dsa_65,
            ),
          },
        };
        const got = hex(bundleHash(bundle));
        assert.equal(got, v.expected_hash_hex, v.name);
        break;
      }
      case "policy_verdict_sign_bytes": {
        const inp = v.input as Record<string, unknown>;
        const v0: PolicyVerdict = {
          version: inp.version as number,
          verdict_id: inp.verdict_id as string,
          agent_id: inp.agent_id as string,
          scope: inp.scope as string,
          allow: inp.allow as boolean,
          context_hash: fromHex(inp.context_hash_hex as string),
          issued_at: inp.issued_at as number,
          valid_until: inp.valid_until as number,
          mac: new Uint8Array(0),
        };
        const got = b64(policyVerdictSignBytesBuf(v0));
        assert.equal(got, v.expected_bytes_b64, v.name);
        break;
      }
      case "verification_receipt_sign_bytes": {
        const inp = v.input as Record<string, unknown>;
        const vp = inp.verifier_pub as { ed25519: string; ml_dsa_65: string };
        const r: VerificationReceipt = {
          version: inp.version as number,
          verifier_id: inp.verifier_id as string,
          verifier_pub: {
            ed25519: fromBase64(vp.ed25519),
            ml_dsa_65: fromBase64(vp.ml_dsa_65),
          },
          bundle_hash: fromHex(inp.bundle_hash_hex as string),
          decision: inp.decision as any,
          human_id: inp.human_id as string | undefined,
          agent_id: inp.agent_id as string | undefined,
          granted_scope: inp.granted_scope as string[] | undefined,
          error_reason: inp.error_reason as string | undefined,
          verified_at: inp.verified_at as number,
          prev_hash: fromHex(inp.prev_hash_hex as string),
          signature: { ed25519: new Uint8Array(0), ml_dsa_65: new Uint8Array(0) },
        };
        const got = b64(verificationReceiptSignBytesBuf(r));
        assert.equal(got, v.expected_bytes_b64, v.name);
        break;
      }
      default:
        throw new Error(`unknown cross-SDK vector kind: ${v.kind}`);
    }
  });
}
