//! Cross-SDK byte-equivalence corpus consumer (SPEC §17.5–§17.6).
//!
//! Loads testvectors/v1/cross_sdk_vectors.json (generated by Go's
//! cmd/ratify-testvectors) and asserts that this SDK produces byte-identical
//! output for every vector. Hub-and-spoke design transitively proves all
//! four reference SDKs are pairwise byte-identical.

use std::fs;
use std::path::PathBuf;

use ratify_protocol::{
    bundle_hash, policy_verdict_sign_bytes_buf, verification_receipt_sign_bytes_buf,
    verifier_context_hash, Constraint, DelegationCert, HybridPublicKey, HybridSignature,
    PolicyVerdict, ProofBundle, VerificationReceipt, VerifierContext,
};
use serde::Deserialize;

#[derive(Debug, Deserialize)]
struct CrossSDKDoc {
    vectors: Vec<CrossSDKVector>,
}

#[derive(Debug, Deserialize)]
struct CrossSDKVector {
    kind: String,
    name: String,
    input: serde_json::Value,
    #[serde(default)]
    expected_hash_hex: Option<String>,
    #[serde(default)]
    expected_bytes_b64: Option<String>,
}

fn vectors_path() -> PathBuf {
    let manifest = env!("CARGO_MANIFEST_DIR");
    PathBuf::from(manifest)
        .join("..")
        .join("..")
        .join("testvectors")
        .join("v1")
        .join("cross_sdk_vectors.json")
}

fn load_vectors() -> Vec<CrossSDKVector> {
    let data = fs::read_to_string(vectors_path()).expect("read cross_sdk_vectors.json");
    let doc: CrossSDKDoc = serde_json::from_str(&data).expect("parse vectors");
    assert!(!doc.vectors.is_empty(), "no vectors");
    doc.vectors
}

fn b64d(s: &str) -> Vec<u8> {
    use base64::{engine::general_purpose::STANDARD, Engine as _};
    STANDARD.decode(s).expect("b64 decode")
}

fn hex_decode(s: &str) -> Vec<u8> {
    hex::decode(s).expect("hex decode")
}

fn pub_key_from_json(v: &serde_json::Value) -> HybridPublicKey {
    HybridPublicKey {
        ed25519: b64d(v["ed25519"].as_str().unwrap()),
        ml_dsa_65: b64d(v["ml_dsa_65"].as_str().unwrap()),
    }
}

fn sig_from_json(v: &serde_json::Value) -> HybridSignature {
    HybridSignature {
        ed25519: b64d(v["ed25519"].as_str().unwrap()),
        ml_dsa_65: b64d(v["ml_dsa_65"].as_str().unwrap()),
    }
}

#[test]
fn cross_sdk_byte_equivalence() {
    for v in load_vectors() {
        match v.kind.as_str() {
            "verifier_context_hash" => check_verifier_context_hash(&v),
            "bundle_hash" => check_bundle_hash(&v),
            "policy_verdict_sign_bytes" => check_policy_verdict(&v),
            "verification_receipt_sign_bytes" => check_verification_receipt(&v),
            other => panic!("unknown vector kind: {}", other),
        }
    }
}

fn check_verifier_context_hash(v: &CrossSDKVector) {
    let inp = &v.input;
    let mut ctx = VerifierContext::default();
    if inp["has_location"].as_bool().unwrap_or(false) {
        ctx.current_lat = inp["current_lat"].as_f64();
        ctx.current_lon = inp["current_lon"].as_f64();
        ctx.current_alt_m = inp["current_alt_m"].as_f64();
    }
    if inp["has_speed"].as_bool().unwrap_or(false) {
        ctx.current_speed_mps = inp["current_speed_mps"].as_f64();
    }
    if inp["has_amount"].as_bool().unwrap_or(false) {
        ctx.requested_amount = inp["requested_amount"].as_f64();
        ctx.requested_currency = Some(
            inp["requested_currency"]
                .as_str()
                .unwrap_or_default()
                .to_string(),
        );
    }
    let got = hex::encode(verifier_context_hash(&ctx).unwrap());
    assert_eq!(
        got,
        v.expected_hash_hex.as_deref().unwrap(),
        "cross-SDK drift for {}",
        v.name
    );
}

fn check_bundle_hash(v: &CrossSDKVector) {
    let raw = &v.input["bundle"];
    let delegations: Vec<DelegationCert> = raw["delegations"]
        .as_array()
        .unwrap()
        .iter()
        .map(|d| DelegationCert {
            cert_id: d["cert_id"].as_str().unwrap().to_string(),
            version: d["version"].as_i64().unwrap() as i32,
            issuer_id: d["issuer_id"].as_str().unwrap().to_string(),
            issuer_pub_key: pub_key_from_json(&d["issuer_pub_key"]),
            subject_id: d["subject_id"].as_str().unwrap().to_string(),
            subject_pub_key: pub_key_from_json(&d["subject_pub_key"]),
            scope: d["scope"]
                .as_array()
                .unwrap()
                .iter()
                .map(|s| s.as_str().unwrap().to_string())
                .collect(),
            constraints: d
                .get("constraints")
                .and_then(|c| c.as_array())
                .map(|arr| {
                    arr.iter()
                        .map(|c| serde_json::from_value::<Constraint>(c.clone()).unwrap())
                        .collect()
                })
                .unwrap_or_default(),
            issued_at: d["issued_at"].as_i64().unwrap(),
            expires_at: d["expires_at"].as_i64().unwrap(),
            signature: sig_from_json(&d["signature"]),
        })
        .collect();
    let bundle = ProofBundle {
        agent_id: raw["agent_id"].as_str().unwrap().to_string(),
        agent_pub_key: pub_key_from_json(&raw["agent_pub_key"]),
        delegations,
        challenge: b64d(raw["challenge"].as_str().unwrap()),
        challenge_at: raw["challenge_at"].as_i64().unwrap(),
        challenge_sig: sig_from_json(&raw["challenge_sig"]),
        session_context: raw
            .get("session_context")
            .and_then(|s| s.as_str())
            .map(b64d)
            .unwrap_or_default(),
        stream_id: raw
            .get("stream_id")
            .and_then(|s| s.as_str())
            .map(b64d)
            .unwrap_or_default(),
        stream_seq: raw.get("stream_seq").and_then(|s| s.as_i64()).unwrap_or(0),
    };
    let got = hex::encode(bundle_hash(&bundle).unwrap());
    assert_eq!(
        got,
        v.expected_hash_hex.as_deref().unwrap(),
        "cross-SDK drift for {}",
        v.name
    );
}

fn check_policy_verdict(v: &CrossSDKVector) {
    use base64::{engine::general_purpose::STANDARD, Engine as _};
    let inp = &v.input;
    let pv = PolicyVerdict {
        version: inp["version"].as_i64().unwrap() as i32,
        verdict_id: inp["verdict_id"].as_str().unwrap().to_string(),
        agent_id: inp["agent_id"].as_str().unwrap().to_string(),
        scope: inp["scope"].as_str().unwrap().to_string(),
        allow: inp["allow"].as_bool().unwrap(),
        context_hash: hex_decode(inp["context_hash_hex"].as_str().unwrap()),
        issued_at: inp["issued_at"].as_i64().unwrap(),
        valid_until: inp["valid_until"].as_i64().unwrap(),
        mac: Vec::new(),
    };
    let bytes = policy_verdict_sign_bytes_buf(&pv).unwrap();
    let got = STANDARD.encode(&bytes);
    assert_eq!(
        got,
        v.expected_bytes_b64.as_deref().unwrap(),
        "cross-SDK drift for {}",
        v.name
    );
}

fn check_verification_receipt(v: &CrossSDKVector) {
    use base64::{engine::general_purpose::STANDARD, Engine as _};
    let inp = &v.input;
    let r = VerificationReceipt {
        version: inp["version"].as_i64().unwrap() as i32,
        verifier_id: inp["verifier_id"].as_str().unwrap().to_string(),
        verifier_pub: pub_key_from_json(&inp["verifier_pub"]),
        bundle_hash: hex_decode(inp["bundle_hash_hex"].as_str().unwrap()),
        decision: inp["decision"].as_str().unwrap().to_string(),
        human_id: inp
            .get("human_id")
            .and_then(|s| s.as_str())
            .unwrap_or_default()
            .to_string(),
        agent_id: inp
            .get("agent_id")
            .and_then(|s| s.as_str())
            .unwrap_or_default()
            .to_string(),
        granted_scope: inp
            .get("granted_scope")
            .and_then(|a| a.as_array())
            .map(|arr| {
                arr.iter()
                    .map(|s| s.as_str().unwrap().to_string())
                    .collect()
            })
            .unwrap_or_default(),
        error_reason: inp
            .get("error_reason")
            .and_then(|s| s.as_str())
            .unwrap_or_default()
            .to_string(),
        verified_at: inp["verified_at"].as_i64().unwrap(),
        prev_hash: hex_decode(inp["prev_hash_hex"].as_str().unwrap()),
        signature: HybridSignature {
            ed25519: Vec::new(),
            ml_dsa_65: Vec::new(),
        },
    };
    let bytes = verification_receipt_sign_bytes_buf(&r).unwrap();
    let got = STANDARD.encode(&bytes);
    assert_eq!(
        got,
        v.expected_bytes_b64.as_deref().unwrap(),
        "cross-SDK drift for {}",
        v.name
    );
}
